### ISSUE TITLE
Use some natural sort for list of speakers

### ISSUE THREAD

**Issue by bittner** [EuroPython/epcon#1008]
The [/events/speakers/](https://ep2019.europython.eu/events/speakers/) page lists all speakers grouped by their first name initial. The sort order is technically correct from a machine point of view. However, non-ASCII initials are grouped separately, which is slightly irritating and somewhat unfair.

*Example:* "Łukasz Kąkol" is listed separately, but should be included in the group of speakers starting with "L" (between "Lilian" and "Lynn").

Is there a humanized, natural sort function or template filter that can take care of this?

**Comment by umgelurgel** [comment]
Thanks for spotting that, @bittner , that's a really good catch. Going to submit a patch for this.

**Comment by umgelurgel** [comment]
```
In [15]: import locale  
    ...: from functools import cmp_to_key                
    ...:  
    ...: locale.setlocale(locale.LC_ALL, '')  
    ...: sorted(['L', 'A', 'Ł', 'Z'], key=cmp_to_key(locale.strcoll))                                                                                                                                       
    ...:  
    ...:                                                                                                                                                                                                    
Out[15]: ['A', 'L', 'Ł', 'Z']
```

**Comment by bittner** [comment]
So, ASCII comes before Eastern Europe. Great. Sounds a bit like, white male comes before colored female or non-binary. Hmm...

I'm not criticizing. Just trying to point out the actual issue.

Ideally, we treat all similar-looking characters the same. Is there an app`^H^H^H^H^H` module for that?

**Comment by hugovk** [comment]
It's a tricky one.

The website is in English, I think it's fair to sort the alphabet according to the English alphabet (whatever than means when it comes to non-ASCII characters!).

For example, where should Ö fall?

* In Swedish: it's at the end of the alphabet, after Z. 
* In Hungarian: it's near the middle, after O.

If the page is in Polish, it would make sense to sort using the Polish alphabet. If French, then sort using the French alphabet.

(Also take into account the country the page is intended for: I wouldn't be totally surprised if two countries which both use the "same" language had different alphabets.)

How should "foreign" letters be sorted for the English alphabet?  https://english.stackexchange.com/a/212630/9001 suggests: "Ignore diacritics when sorting English — except to break ties", which is what `locale` is doing in https://github.com/EuroPython/epcon/issues/1008#issuecomment-495541266.

(That link also goes into details about sorting of names which complicates things further, but keep it simple with something like `locale`!)

**Comment by bittner** [comment]
Without getting too academic or religious about things, my proposal was to group visually similar letters into what is the visual equivalent in English. English is the lingua franca at EuroPython, I assume.

Hence:

* A = Ä, Â, À, Á, Ẵ, Ẫ, Ã, ...
* E = Ê, Ễ, Ḛ, ...
* I = Î, Ì, Í, Ĩ, ...
* J = Ĵ, ...
* L = Ł, Ɫ, ...
* O = Ö, Ô, Ó, Ò, Ṍ, Ṏ, ...
* U = Ü, Û, Ù, Ú, Ữ, ...
* V = Ṽ, ...

There should be a package or module doing that already, shouldn't it? The `upper` and `lower` string methods handle those characters out of the box in Python, by the way.

**Comment by rciorba** [comment]
I've whipped up a package to help with this: https://pypi.org/project/anglicize/ 
I can't really find where in epcon this `events/speakers/` view is implemented. If someone wants to point me in the right direction, I'd be happy to write a PR.

**Comment by malemburg** [comment]
Hi Radu,

the speaker and session listings use template tags and are
rendered directly on the page (to stay flexible).

Here's the code for the speakers page:

"""
{% load sessions %}
{% speakers "ep2020" as speakerdata %}

{% for name, group in speakerdata.groups_list %}
<h3>{{ name }} ...</h3>
<ul>
{% for speaker in group %}
<li><a href="{{ speaker.url }}">{{ speaker.fullname }}</a></li>
{% endfor %}
</ul>
{% endfor %}

<p>{{ speakerdata.count }} speakers in total.</p>
"""

On 3/8/2020 2:03 PM, Radu Ciorba wrote:
> I've whipped up a package to help with this:
> https://pypi.org/project/anglicize/
> I can't really find where in epcon this |events/speakers/| view is
> implemented. If someone wants to point me in the right direction, I'd be
> happy to write a PR.


-- 
Marc-Andre Lemburg
http://www.malemburg.com/
