### ISSUE TITLE
Use real words for variables in templates

### ISSUE THREAD

**Issue by bittner** [EuroPython/epcon#1009]
In [/ep2019/templates/conference/render_schedule_list.html](https://github.com/EuroPython/epcon/blob/ep2019/templates/conference/render_schedule_list.html) there are for-loops with single-letter variables. This makes the code terribly hard to read and understand.

Same goes for other templates, such as `render_place.html`, `render_schedule2.html`, etc.

Think: "What is e? Event?", "What is s? Schedule? Speaker?", "What is r? Ah, randint. But what the heck ... what does it mean, what is its intention?"

(If there was a Pylint going over that code it would complain quite a lot. For a reason.)

We need to keep the code base readable. Self-explanatory. Beautiful.

**Comment by umgelurgel** [comment]
:100:% agreed - a large chunk of the website has been rewritten for this year's conference and a lot of the existing views and templates are waiting to be deprecated; it won't happen until after the conference though.

The templates you're referencing is on the list to be deprecated - if there's a view that's not using the templates from [/ep19/bs/](https://github.com/EuroPython/epcon/tree/ep2019/templates/ep19), that's probably a bug.

Does pylint support linting django templates?

**Comment by bittner** [comment]
> Does pylint support linting django templates?

Don't think so. And even `django-lint` looks more like an advertisement. Could be a start, though.

**Comment by umgelurgel** [comment]
We're in the process of removing a lot of the offending templates, new templates follow this practice. Going to resolve this ticket, thanks for bringing this issue up!
