### ISSUE TITLE
PyData Sessions list on webpage

### ISSUE THREAD

**Issue by alanderex** [EuroPython/epcon#1011]
I want a session list for PyData only, similar to
https://ep2019.europython.eu/events/sessions/#Training-sessions

In the database in conference_talks  all PyData sessions have the domain **pydata** 
Guess we are just missing session.**domain** in the sessionlist

The draft page is already up,
should work as soon as session has a domain attribute 
https://ep2019.europython.eu/pydata-session-europython

**Comment by malemburg** [comment]
This is implemented now.
