### ISSUE TITLE
Content: Conference schedule is hard to find

### ISSUE THREAD

**Issue by bittner** [EuroPython/epcon#1013]
(I hope it's correct to report content issues of the EuroPython website here, too!)

I was trying to find the conference schedule on the website in order to be able to tell on which days I will attend. It was a very bumpy ride. After minutes of surfing the site I figured it's on the home page in the lower half.

Can you please:

- add the conference schedule to the [Program page](https://ep2019.europython.eu/events/)
- remove the weird "Please see the "Program" menu for details" sentence (which is actually just telling that the navigation and/or information architecture of the site is broken)
- add a link to the [Program page](https://ep2019.europython.eu/events/) to the footer's "Program" section (which is currently missing a link to that page)

Thank you!

**Comment by malemburg** [comment]
Fixed. Thanks for the report.

**Comment by bittner** [comment]
Thanks for updating! :1st_place_medal:
