### ISSUE TITLE
Web shop has to provide sections for events and other items

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1014]
We need to start selling tickets for the social event (category: event) and the SIM cards (category: other), but the webshop currently has no way of selecting items from these categories.

**Comment by malemburg** [comment]
It's probably best to have a single additional option in the shop system, which then shows all non-conference ticket types and doesn't differentiate between recipient types.

**Comment by umgelurgel** [comment]
Fixed in https://github.com/EuroPython/epcon/pull/1021
