### ISSUE TITLE
404: privacy_settings

### ISSUE THREAD

**Issue by hugovk** [EuroPython/epcon#1018]
https://ep2019.europython.eu/registration/tips-for-attendees/ has a "privacy settings" link to https://ep2019.europython.eu/user-panel/privacy_settings/ but it's a 404.

Replacing the underscore with a dash works:

https://ep2019.europython.eu/user-panel/privacy-settings/

**Comment by umgelurgel** [comment]
Thanks for reporting this! Should be fixed now.
