### ISSUE TITLE
Discount Code not working - TLK-THIFPJ 25%

### ISSUE THREAD

**Issue by lnandi1** [EuroPython/epcon#1019]
Hello,

I am a speaker and have been assigned a discount code TLK-THIFPJ 25% but the website says that it is valid or expired. I am not sure who to approach about this. I think I have approached the wrong people. Please can this be fixed.
My email is: lnandi337@gmail.com

Thank you

**Comment by malemburg** [comment]
Please send an email to our helpdesk@europython.eu. They will be able to help you.
