### ISSUE TITLE
Ticket stats entry for tickets with unique emails is missing

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1028]
We had such an entry for EP2018 and it was useful to at least estimate the total number of attendees, given that we have two ticket types (training and conference, with some overlap):

https://ep2018.europython.eu/admin/conference/conference/ep2018/stats/

**Comment by umgelurgel** [comment]
Looks like the changes from https://github.com/EuroPython/epcon/pull/787/files might have been merged into ep2018 and did not make it to the dev/ep2019 branch - going to restore them.

**Comment by europython-society** [comment]
Could be, thanks for checking.

On 07.06.2019 10:48, umgelurgel wrote:
> Looks like the changes from
> https://github.com/EuroPython/epcon/pull/787/files might have been
> merged into ep2018 and did not make it to the dev/ep2019 branch - going
> to restore them.

-- 
Marc-Andre Lemburg
eGenix.com

Professional Python Services directly from the Experts (#1, Jun 07 2019)
>>> Python Projects, Coaching and Consulting ...  http://www.egenix.com/
>>> Python Database Interfaces ...           http://products.egenix.com/
>>> Plone/Zope Database Interfaces ...           http://zope.egenix.com/
________________________________________________________________________

::: We implement business ideas - efficiently in both time and costs :::

   eGenix.com Software, Skills and Services GmbH  Pastor-Loeh-Str.48
    D-40764 Langenfeld, Germany. CEO Dipl.-Math. Marc-Andre Lemburg
           Registered at Amtsgericht Duesseldorf: HRB 46611
               http://www.egenix.com/company/contact/
                      http://www.malemburg.com/
