### ISSUE TITLE
Slide upload functionality is missing from talk pages

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1038]
Speakers need to be able to upload their slides to the EP2019 website, just like it was in previous year. This functionality is no longer available, it seems, e.g.

https://ep2019.europython.eu/talks/hYAEdqK-europython-2020-help-us-build-the-next-edition/

We will need to readd this, since we ideally want to have all slides available on our website:

https://ep2019.europython.eu/events/call-for-proposals/#Release-agreement-for-submissions

**Comment by umgelurgel** [comment]
Should the link to the slides become available on the public talk page as soon as they're uploaded?
