### ISSUE TITLE
Make links in talk description clickable

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#1046]
Especially useful for tutorials, but could be useful in regular talks as well
Basically if a link is included in the description, like here -> https://ep2019.europython.eu/talks/TSm3eP3-explaining-ai-to-managers/

It should be clickable. :)

**Comment by umgelurgel** [comment]
Hm, I don't see the link in the description - maybe it has been updated. So basically, currently we render plain text, while we want to have it rendered as html?

**Comment by artcz** [comment]
Yes, so this is just note from @alanderex – I just linked a random talk to make sure we have a link to an example page, but looks like this one -> https://ep2019.europython.eu/talks/KT8M8bu-analytics-with-pandas-and-jupyterlab/ has some example.

I don't think rendered as the html is a full answer – but some filter that wraps things that looks like urls in a `<a href={url}>{url}</a>`

(edited because github rendered the `<a>` as a link...)
