### ISSUE TITLE
Cannot edit talk proposal

### ISSUE THREAD

**Issue by lordmauve** [EuroPython/epcon#106]
When trying to edit my talk proposal (to fix the wording and add some tags), saving does not work. At the top of the form, I see the messages

```
slides_agreement
    This field is required.
video_agreement
    This field is required.
```

and the entry is not updated.

Additionally, these messages are displayed in plain text rather than like error messages.

**Comment by shimizukawa** [comment]
same to me https://twitter.com/shimizukawa/status/578231565316022272

**Comment by malemburg** [comment]
The fields are available now, but apparently the view doesn't provide the values to the fields, so you have to check them again each time you edit a talk.

**Comment by malemburg** [comment]
Please try again now. Editing should work.

**Comment by shimizukawa** [comment]
I got. Now I can update my proposal. Thanks!
