### ISSUE TITLE
Talk voting  should only be allowed for users with tickets

### ISSUE THREAD

**Issue by xmatthias** [EuroPython/epcon#1080]
The Talk proposals are only shown to users with tickets - but can be voted on by users without tickets, so once a user knows the url that user can vote from multiple accounts

**Comment by xmatthias** [comment]
After digging into this i don't think this is actually a problem.

Since the voting-form is protected using [django csrf](https://docs.djangoproject.com/en/2.2/ref/csrf/), a non-logged in user (or a user without ticket) won't have the "csrfmiddlewaretoken" to make the post-request successfully, so no votes will be registered in this case.

**Comment by aramboi** [comment]
While the CSRF protection we get for free is a nice side-effect, I still think we should check that the user has a ticket as a way to restrict some sections of the website. We should probably have a view decorator that handles that check, similar to [`login_required`](https://docs.djangoproject.com/en/2.2/topics/auth/default/#the-login-required-decorator) - though I am not sure how that integrates with django-cms.

**Comment by xmatthias** [comment]
Using a decorator would require a default-redirect like for login (go to login/signup page) - or at least a default answer page.

I don't see this for "ticket_required" - where should a redirect bring users to so it's clear that they'd need to have a ticket for this action (especially vote - where we're not showing vote options for users without ticket - and voting itself is basically a api action).
