### ISSUE TITLE
add `python manage.py makemigrations` to `make db` command in Makefile

### ISSUE THREAD

**Issue by zevaverbach** [EuroPython/epcon#1085]
I had to do this manually while setting up to contribute.  I can do a PR implementing this?

**Comment by artcz** [comment]
Hi Zev,
Thanks for adding the issue, but this is not strictly speaking correct – `makemigrations` should happen only if you change something in the database, the `make db` step should only run `migrate` which applies already made migrations.

**Comment by artcz** [comment]
Closing for now.
