### ISSUE TITLE
Helpdesk durations missing in CFP form

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#109]
From the helpdesk:
1. The list is still missing help desk durations (and actually, nowhere
   does it say how long the help desk session is supposed to be).

The latter is not quite true anymore, since we've added that information yesterday.

**Comment by malemburg** [comment]
Actually, I just checked: we only added that the helpdesk tickets are for 30 minutes, but don't say how long the helpdesks will be open.

**Comment by umgelurgel** [comment]
As the CFP flow has been rewritten for 2019, this should be safe to resolve.
