### ISSUE TITLE
Ticket purchase page should be followed by ticket configuration/assignment

### ISSUE THREAD

**Issue by umgelurgel** [EuroPython/epcon#1095]
> At the end of the process, have a prompt that states the ticket number, with a short sentence explaining they need this number to collect badges.

The way I'd see it, the purchase confirmed screen should show a formset handling ticket assignment, and a `continue` button taking the user to a formset of ticket configuration. WDYT @aramboi / @artcz / @hypha ?

**Comment by aramboi** [comment]
That sounds good to me. This way maybe we get the t-shirt sizes early on. :)

**Comment by hypha** [comment]
Sounds good to me. And if we like the ticket preview idea, it could be after the ticket configuration form?

**Comment by switowski** [comment]
The #1148 adds management buttons after the ticket is purchased.

I think it looks nicer especially for a bigger order and it doesn't force the user to go through additional steps (forms) after purchasing the tickets. If you think that it's enough for now, we can close this issue.

**Comment by umgelurgel** [comment]
I think we should be all set with this enhancement - thanks for your work on this, @switowski !
