### ISSUE TITLE
Remove the support of wkhtmltopdf ?

### ISSUE THREAD

**Issue by matrixise** [EuroPython/epcon#1170]
In the Dockerfile, there is a reference to wkhtmltopdf, but in the code, I don't see any call to `wkhtmltopdf` or `wkhtmltoimage`.

@aramboi any idea?

**Comment by europython-society** [comment]
AFAIK, the tool is used for generating PDF invoices.

On 29.01.2020 13:39, Stéphane Wirtel wrote:
> In the Dockerfile, there is a reference to wkhtmltopdf, but in the code, I don't see any call to `wkhtmltopdf` or `wkhtmltoimage`.
> 
> @aramboi any idea?
> 

-- 
Marc-Andre Lemburg
eGenix.com

Professional Python Services directly from the Experts (#1, Jan 29 2020)
>>> Python Projects, Coaching and Support ...    https://www.egenix.com/
>>> Python Product Development ...        https://consulting.egenix.com/
________________________________________________________________________

::: We implement business ideas - efficiently in both time and costs :::

   eGenix.com Software, Skills and Services GmbH  Pastor-Loeh-Str.48
    D-40764 Langenfeld, Germany. CEO Dipl.-Math. Marc-Andre Lemburg
           Registered at Amtsgericht Duesseldorf: HRB 46611
               https://www.egenix.com/company/contact/
                     https://www.malemburg.com/

**Comment by matrixise** [comment]
ok, but I don't see any reference. Where is the reference to this tool? Thank you.

**Comment by malemburg** [comment]
Correction: We used to use it. The current code instead uses
WeasyPrint (https://github.com/Kozea/WeasyPrint/).

https://github.com/EuroPython/epcon/blob/dev/ep2020/common/http.py

-- 
Marc-Andre Lemburg
eGenix.com

Professional Python Services directly from the Experts (#1, Jan 29 2020)
>>> Python Projects, Coaching and Support ...    https://www.egenix.com/
>>> Python Product Development ...        https://consulting.egenix.com/
________________________________________________________________________

::: We implement business ideas - efficiently in both time and costs :::

   eGenix.com Software, Skills and Services GmbH  Pastor-Loeh-Str.48
    D-40764 Langenfeld, Germany. CEO Dipl.-Math. Marc-Andre Lemburg
           Registered at Amtsgericht Duesseldorf: HRB 46611
               https://www.egenix.com/company/contact/
                     https://www.malemburg.com/

**Comment by matrixise** [comment]
ok, so in this case, we can remove `wkhtmltopdf`!

@malemburg / @umgelurgel  Do you confirm? Thank you

**Comment by umgelurgel** [comment]
Once you make sure it's not a dependency of wasyprint, should be safe to remove. Thanks!
