### ISSUE TITLE
Change wording of privacy notice banner

### ISSUE THREAD

**Issue by hypha** [EuroPython/epcon#1198]
The privacy banner on the website says "agreed". It's not wrong, but it can be a bit misleading. People might interpret it as "I've already agreed to it". It's probably better to be as explicit as possible and say e.g. "I agree" or "I'm OK with it" or even just "OK" is probably a bit clearer.

![image](https://user-images.githubusercontent.com/6319134/74537472-12c3c380-4f32-11ea-84f5-e50a189dd617.png)

**Comment by hugovk** [comment]
Please see PR #1207.
