### ISSUE TITLE
Email reset link contains references to EuroPython 2019

### ISSUE THREAD

**Issue by matrixise** [EuroPython/epcon#1204]
Because I wanted to test the reset password feature, I have received an email with some references to EP2019

```
Hello!

We sent you this email because you (or someone using your email address) requested a password reset for your user account at ep2020.europython.eu

Here's the link:

Use the link to change your password. If you suddently remembered your password – you can just ignore the link.

However – if you didn't ask for the password reset – please let us know.

You can find up to date contact information at the website https://ep2020.europython.eu

Thanks,
EuroPython2019 Team
```

Same for the subject

**Comment by matrixise** [comment]
The issue is the ep19 template, could we copy this directory to ep2020, and fix the templates and the code calling these templates.

**Comment by umgelurgel** [comment]
Thanks for catching this - the email template directories are part of the repo.

**Comment by malemburg** [comment]
It would be better to rename the dir from "ep19" to "europython".
We won't be having multiple years run off of the same branch.

On 20.02.2020 17:14, Stéphane Wirtel wrote:
> The issue is the ep19 template, could we copy this directory to ep2020,
> and fix the templates and the code calling these templates.

-- 
Marc-Andre Lemburg
eGenix.com

Professional Python Services directly from the Experts (#1, Feb 20 2020)
>>> Python Projects, Coaching and Support ...    https://www.egenix.com/
>>> Python Product Development ...        https://consulting.egenix.com/
________________________________________________________________________

::: We implement business ideas - efficiently in both time and costs :::

   eGenix.com Software, Skills and Services GmbH  Pastor-Loeh-Str.48
    D-40764 Langenfeld, Germany. CEO Dipl.-Math. Marc-Andre Lemburg
           Registered at Amtsgericht Duesseldorf: HRB 46611
               https://www.egenix.com/company/contact/
                     https://www.malemburg.com/

**Comment by malemburg** [comment]
Fixed by https://github.com/EuroPython/epcon/pull/1206
