### ISSUE TITLE
Blog redirects to Tumblr homepage

### ISSUE THREAD

**Issue by hugovk** [EuroPython/epcon#1229]
Visiting https://blog.europython.eu/ takes me to the Tumblr privacy consent page, and then the Tumblr homepage https://www.tumblr.com:

![image](https://user-images.githubusercontent.com/1324225/75879077-633c8b80-5e23-11ea-9e93-17c0cb2fe6b5.png)

![image](https://user-images.githubusercontent.com/1324225/75879087-68013f80-5e23-11ea-849d-a45976791dd8.png)

**Comment by malemburg** [comment]
Yes, that's unfortunately correct. Tumblr deleted our blog yesterday without notice or explanation. This could be a technical issue at Tumblr, and hopefully we can get it restored.

**Comment by umgelurgel** [comment]
The blog has been restored.
