### ISSUE TITLE
Broken link to social media channels

### ISSUE THREAD

**Issue by hugovk** [EuroPython/epcon#1237]
1. Go to https://ep2020.europython.eu/registration/buy-tickets/
2. Click "Please stay tuned and watch our social media channels."

# Actual

404 https://ep2020.europython.eu/europython/social/

# Expected

https://ep2020.europython.eu/social-media/

**Comment by hypha** [comment]
Should be fixed now. Thanks.

**Comment by hugovk** [comment]
Confirmed, thanks!

**Comment by malemburg** [comment]
Thanks for the report. I also added a redirect for the URL to the correct one.
