### ISSUE TITLE
Location Link on 2020 site takes you to 2019 location page

### ISSUE THREAD

**Issue by GadgetSteve** [EuroPython/epcon#1239]
Clicking on the word "Location" at the top of any of the pages for the 2020 site takes you to a page about Basel rather than Dublin.

**Comment by europython-society** [comment]
On 3/11/2020 12:11 PM, Steve (Gadget) Barnes wrote:
> Clicking on the work Location in any of the pages for the 2020 site
> takes you to a page about Basel rather than Dublin.

Could you please give an example (with URL), since I'm not able
to find any such links on the pages I checked.

Thanks,
-- 
Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by GadgetSteve** [comment]
If you navigate to https://ep2020.europython.eu/registration/buy-tickets/ and on the very top (menu) line locate the word "Location" (between "Program" and "Sponsor") then when you hover you get a drop down but if you click on the actual word "Location" you get taken to https://ep2020.europython.eu/location/ which starts with:
Location
Welcome to Basel

Likewise if you click on "Come to Dublin" in the drop down you do get a page on Dublin (https://ep2020.europython.eu/location/come-to-dublin/) the second line of which reads:

Home / Location / Come to Dublin

If you click on the second word of that set of links you get to the Basel page again.

**Comment by GadgetSteve** [comment]
Just checked on the mobile view and in the drop down clicking on the actual word location does the same.

**Comment by malemburg** [comment]
Ok, thanks. I see what you mean and have done some basic editing to fix this.

I had originally understood that there's a link back to the ep2019 website and was trying to find this.

**Comment by GadgetSteve** [comment]
Looks good!
