### ISSUE TITLE
People cant submit talks in languages that is not English 

### ISSUE THREAD

**Issue by oiertwo** [EuroPython/epcon#125]
Hi,

I'm trying to change the language of 2 proposals to Spanish and
doesn't work. If I set it to English, every thing works.

Regards.

**Comment by malemburg** [comment]
Looks like a duplicate of #116.

**Comment by alexsavio** [comment]
has this been solved?

**Comment by europython-society** [comment]
On 02.09.2016 12:23, Alexandre M. S. wrote:

> has this been solved?

I thin so, since we do have talks in Spanish/Basque in the database.

## 

Marc-Andre Lemburg
eGenix.com
