### ISSUE TITLE
Talks disappearing from my list of talks?

### ISSUE THREAD

**Issue by ionelmc** [EuroPython/epcon#126]
After I edit a talk it disappears from the list of talks in my profile. What's going on?

This is my profile: https://ep2015.europython.eu/conference/p/ionel-cristian-maries 

I should see 2 talks there but there's only one :confused:

**Comment by ionelmc** [comment]
Seems it reappears after few minues? Is there some _too-aggressive_ caching?

**Comment by malemburg** [comment]
I can see two talks as well. It's possible that caching is going on somewhere. The site itself is not behind a cache like fastly or cloudflare, though.
