### ISSUE TITLE
2019 page / website: Internal Server Error

### ISSUE THREAD

**Issue by riccardoporreca** [EuroPython/epcon#1297]
The 2019 EuroPython website https://ep2019.europython.eu/, currently listed under the EuroPython menu, gives an "Internal Server Error"

![image](https://user-images.githubusercontent.com/13663564/83513168-aa452600-a4d1-11ea-9f75-519508bec4df.png)

**Comment by malemburg** [comment]
Thanks for the report. I can confirm that there's a problem.

**Comment by malemburg** [comment]
Should be working again now.

**Comment by riccardoporreca** [comment]
Great, thanks for the prompt action @malemburg!
