### ISSUE TITLE
Sponsor need to be sorted descending by sponsor amount

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1304]
They appear to be sorted alphabetically:

![image](https://user-images.githubusercontent.com/6735498/86386917-b2d87a00-bc92-11ea-96f1-1f031754ae62.png)

**Comment by matrixise** [comment]
;-) sorry, I was happy to be on the top ;-) next year, I need to be a bigger sponsor. @malemburg

**Comment by fpierfed** [comment]
This was apparently closed by #1314
