### ISSUE TITLE
Add schedule information to the talk page

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1305]
Example:

![image](https://user-images.githubusercontent.com/6735498/87029424-7354e500-c1e0-11ea-8b26-308457e77f2c.png)

Ideally, this should also work with the timezones script we have on the schedule.

**Comment by hypha** [comment]
FYI, when you click See in schedule, the URL does not contain any time information, e.g. the talk in the screenshot will return this URL: https://ep2020.europython.eu/schedule/23-july?selected=8DboZjY-speed-up-your-data-processing But if you add the time at the end of the URL, then you'd be directed to the correct place on the schedule, i.e. https://ep2020.europython.eu/schedule/23-july?selected=8DboZjY-speed-up-your-data-processing#11:15-UTC
