### ISSUE TITLE
Talk missing UUID when being set up manually

### ISSUE THREAD

**Issue by hypha** [EuroPython/epcon#1311]
When an admin manually sets up a talk, e.g. for a sponsor or a keynote, the talk does not pick up a UUID (see screenshot example below)
![image](https://user-images.githubusercontent.com/6319134/87794998-5c953a80-c83f-11ea-9989-9819935dd3f9.png)

A regular talk that went through cfp has a UUID, e.g. 
![image](https://user-images.githubusercontent.com/6319134/87795540-20160e80-c840-11ea-8d65-9a785fe46512.png)

Without a UUID as part of the talk URL, when the speaker of this manually set up talk tries to update the talk on their own, they hit 500.

**Comment by matrixise** [comment]
I do confirm the issue

**Comment by matrixise** [comment]
@malemburg to be sure, is it a feature or a bug that the user can fill the slug field?

**Comment by matrixise** [comment]
After discussion with @malemburg and @hypha, I am going to close this issue because it's an intentional feature.
