### ISSUE TITLE
Broken link: https://twitter.com/https://twitter.com/username

### ISSUE THREAD

**Issue by hugovk** [EuroPython/epcon#1312]
# Steps to reproduce

1. Visit https://ep2020.europython.eu/profiles/dustin-ingram/
-> Twitter says `di_codes` ✅
2. Click it
-> Goes to https://twitter.com/di_codes ✅

3. Visit https://ep2020.europython.eu/profiles/jason-mcdonald/
-> Twitter says `https://twitter.com/codemouse92` :x:
4. Click it
-> Goes to https://twitter.com/https://twitter.com/codemouse92 :x:

# Expected

3. says `codemouse92` ✅ 
4. goes to https://twitter.com/codemouse92 ✅ 

Two possible general fixes:

* Fix existing bad data: if there's a link like https://twitter.com/https://twitter.com/codemouse92, fix it by perhaps stripping the username out of `https://twitter.com/codemouse92` before prepending `https://twitter.com/`

* Validate in the first place: either don't let people enter a full URL in the first place or fix it for them

**Comment by matrixise** [comment]
- [x] Cleanup of the database
- [x] Fix the code
