### ISSUE TITLE
OAuth via Google not working for site

### ISSUE THREAD

**Issue by dvaruas** [EuroPython/epcon#1369]
Failed Login to the EuroPython site via Google. Refer to the screenshot attached. 
![Screenshot from 2021-04-16 14-31-53](https://user-images.githubusercontent.com/3855435/115024762-27a53980-9ede-11eb-9d65-ae0a7413a941.png)

**Comment by malemburg** [comment]
Should be fixed now. We forgot to add the new URL to the Google OAuth setup.

Thanks for the report.
