### ISSUE TITLE
New livestream-only ticket cannot be added to the cart

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1374]
![image](https://user-images.githubusercontent.com/6735498/115239546-29117480-a11f-11eb-85f0-9ce972de6dc9.png)

Even when adding the ticket together with some other ticket, it doesn't show up in the order list in step 2:

![image](https://user-images.githubusercontent.com/6735498/115239644-421a2580-a11f-11eb-97d3-1fb14c213b15.png)

**Comment by malemburg** [comment]
It's possible that the shop system hardcodes the ticket types somewhere.

Note: I have not yet added the new type to the list we have here: https://github.com/EuroPython/epcon/blob/ep2021/conference/fares.py

Could be that this is causing the problem.

**Comment by fpierfed** [comment]
Fixed in 7f5ddf805582ad59616f71e6a18a28623f23b07b
