### ISSUE TITLE
HTML markup for Django admin fields no longer works

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1376]
E.g. in the ticket admin page we see the HTML  and not the rendered version.

See https://stackoverflow.com/questions/42316686/django-how-does-allow-tags-and-short-description-works for details.

Apparently the .allow_tags attribute was removed in Django 1.11.

**Comment by fpierfed** [comment]
The issue appears, at the very least, in
Conference › Attendee profiles
Conference › Tickets

**Comment by hypha** [comment]
I've tried the approach of adding the decorator @mark_safe according to this and it seems to have done it: https://stackoverflow.com/questions/47953705/how-do-i-use-allow-tags-in-django-2-0-admin   
Just  `from django.utils.safestring import mark_safe` in these files: `p3/admin.py`, `conference/admin.py` and `assopy/admin.py` and above each function that uses "allow_tags", add the `@mark_safe`
No idea if it makes sense.

**Comment by malemburg** [comment]
Sounds good. We need to fix all such methods in p3/admin.py, assopy/admin.py and conference/admin.py. Alternatively, we could use the function directly in those methods.
