### ISSUE TITLE
Create streams page on EP2021

### ISSUE THREAD

**Issue by fpierfed** [EuroPython/epcon#1377]
This should be a Django-cms page that uses the "tickets" template tag (defined in "conference") to identify folks who have a sprint-only ticket and show them the YouTube/Vimeo streams.

Example usage of the tag
```
{% load conference %}

{% if user.is_authenticated %}
You are logged in and these are your tickets: {% tickets user as tickets %}
{% for ticket in tickets %}
<p>
  {{ ticket }}, which is assigned to user ID {{ ticket.user }}
  {% if user == ticket.user %}
    which is you
  {% else %}
    which is somebody else 
  {% endif %}
({{ ticket.name }})
</p>
{% endfor %}
{% else %}
Booo! You need to login.
{% endif %}
```

**Comment by fpierfed** [comment]
One could also test it locally by creating a stream-only ticket (fares TRVP or TRVC), assign it to Alice or Bob and then just create a page where the ticket holder can see a random YouTube Video or something like that :-)

**Comment by malemburg** [comment]
We are working on this in our Python Meeting Düsseldorf Sprint at the moment.

The page will have to adapt to different stream URLs each part of the day and not only work for stream only ticket holders, but for all conference ticket holders as well.

**Comment by malemburg** [comment]
We have a first prototype of the "Streams" page done. Will clean it up and merge tomorrow.

**Comment by fpierfed** [comment]
Fantastic!!!!!

**Comment by malemburg** [comment]
Since the page will be shown in the EP2021 website, we should add a new template which only includes the menu bar, the stream selector and a few high tier sponsor logos.

This will require adding a new template to the system.

**Comment by malemburg** [comment]
Should be done now. Still missing is the CMS template plugin code, which has to be added to the CMS via the web.

**Comment by malemburg** [comment]
Something else to do:
- add streamset permissions to Conference Admin group
