### ISSUE TITLE
Ask Speakers About Their Preferred/Not Available Timezone(s)

### ISSUE THREAD

**Issue by fpierfed** [EuroPython/epcon#1378]
We need to add a popup menu or some other widget on the proposal submission page. Make it required with no default. We need to decide if the question is positive or negative.

**Comment by malemburg** [comment]
I would suggest to simply add a free text field. Our conference runs for several days and the constraints may well be more complex than just related to time zones.

**Comment by malemburg** [comment]
Or we could have a drop-down with options: 08-12 CEST, 12-16 CEST, 16-20 CEST. This may be better to automatic scheduling, in case we will use this.
