### ISSUE TITLE
Anchors to section titles on longer pages don't work

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1380]
E.g. https://ep2021.europython.eu/registration/buy-tickets/#Ticket-Tiers
or https://ep2021.europython.eu/events/call-for-proposals/#Presenting-at-EuroPython

The TOC script takes too long to set the anchors on the sections and so the browser doesn't scroll to the right section. I guess we need to add some JS to force scrolling to the right anchor after the TOC script is done.

**Comment by hypha** [comment]
Btw, I noticed the bug a while ago. So I've inserted quite a few anchor tags in some pages when I was doing the editing which works. For example, https://ep2021.europython.eu/registration/buy-tickets/#sprint would work.

**Comment by malemburg** [comment]
Additional fixes to make this more robust: #1385
