### ISSUE TITLE
[ep-matrix] Show custom roles in element

### ISSUE THREAD

**Issue by gilgamezh** [EuroPython/epcon#1408]
Some related notes: https://gist.github.com/Woile/129006fb37b73d3dfdaeb271fe03d94f

Power levels match to custom roles: 
`` 
{
  "3": "Attendee",
  "6": "Sponsor",
  "9": "Sprinter",
  "12": "Speaker",
  "15": "Staff"
}
```

@Woile is working on a change in Element to support it.

some important ⚠️  is that it will be working only in our Element client. Other clients are not going to see it.

**Comment by fpierfed** [comment]
Closed by https://github.com/EuroPython/matrix-react-sdk/commit/a950f490852c3c17aebd5edd05b7305e37269c18
