### ISSUE TITLE
Matrix sign-in doesn't work with epcon auth if the user names contain space or non-ascii characters

### ISSUE THREAD

**Issue by hypha** [EuroPython/epcon#1424]
The localpart of the user ID on matrix has strict rules: https://matrix.org/docs/spec/appendices#user-identifiers
At the moment, if the user's first name or last names contain spaces, or possibly non-ASCII characters, they cannot sign in via the epcon-auth. And the error message is very helpful: This homeserver does not support login using email address.  homeserver.log provides more debugging info.

**Comment by malemburg** [comment]
I believe changing the way the Matrix user name is built will fix this implicitly: #1425

**Comment by fpierfed** [comment]
Fixed by using the epcon username
