### ISSUE TITLE
Matrix user names should not include first and last name

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1425]
See https://github.com/EuroPython/ep-matrix/blob/epcon_auth/epcon_auth_provider/epcon_auth_provider.py#L226

The auth mechanism currently uses ```return strip_accents(f"{first_name}.{last_name}.{username}".lower())```

This should be ```return strip_accents(f"{username}".lower())``` and would then also avoid issues with accents, spaces, etc.

**Comment by fpierfed** [comment]
Fixed by using the epcon username.
