### ISSUE TITLE
Anchor on schedule page does not work

### ISSUE THREAD

**Issue by hypha** [EuroPython/epcon#1430]
Currently, if you go to any talk, e.g. https://ep2021.europython.eu/talks/BSqTuAU-thoughts-on-the-future-of-python/, click "See in Schedule", it does not direct you to the right anchor. Might be related to https://github.com/EuroPython/epcon/issues/1380

**Comment by malemburg** [comment]
Fixed in https://github.com/EuroPython/epcon/pull/1435
