### ISSUE TITLE
[ep-matrix] Turn off the invite buttons in the rooms

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1431]
![image](https://user-images.githubusercontent.com/6735498/121773011-805d1f80-cb79-11eb-9d27-0cbc34986aea.png)

**Comment by malemburg** [comment]
This appears to be a permission setting on the room:

![image](https://user-images.githubusercontent.com/6735498/121776566-e9e72900-cb8d-11eb-8205-0a60d00f654b.png)

**Comment by fpierfed** [comment]
Shall we restrict invites to moderators?

**Comment by europython-society** [comment]
On 17.06.2021 22:14, Francesco Pierfederici wrote:
> Shall we restrict invites to moderators?

Yes, sounds good.

**Comment by fpierfed** [comment]
Done (see https://github.com/EuroPython/ep-matrix/commit/3fe9ecb2c2dde2c69a39f789e3d5997ed65e2817)
