### ISSUE TITLE
Talk title should be stripped before insertion in DB

### ISSUE THREAD

**Issue by alexsavio** [EuroPython/epcon#152]
I am getting some errors processing the talks for the booklet.

I think the best way to solve this is to process the title before insertion:
- strip
- have double space "  " replaced by " "
- if the title starts and ends with quotes: remove them

**Comment by malemburg** [comment]
On 03.06.2015 08:40, Alexandre M. S. wrote:

> I am getting some errors processing the talks for the booklet.
> 
> I think the best way to solve this is to process the title before insertion:
> - strip
> - have double space "  " replaced by " "
> - if the title starts and ends with quotes: remove them 

Right. That's what I'm already doing in the script to generate the
talk list:

https://github.com/EuroPython/epcon/blob/develop/p3/management/commands/accepted_talks.py#L48

(except for the folding of additional spaces)

## 

Marc-Andre Lemburg
eGenix.com

Professional Python Services directly from the Source  (#1, Jun 03 2015)

> > > Python Projects, Coaching and Consulting ...  http://www.egenix.com/
> > > mxODBC Plone/Zope Database Adapter ...       http://zope.egenix.com/
> > > mxODBC, mxDateTime, mxTextTools ...        http://python.egenix.com/
> > > 
> > > ---

::::: Try our mxODBC.Connect Python Database Interface for free ! ::::::

   eGenix.com Software, Skills and Services GmbH  Pastor-Loeh-Str.48
    D-40764 Langenfeld, Germany. CEO Dipl.-Math. Marc-Andre Lemburg
           Registered at Amtsgericht Duesseldorf: HRB 46611
               http://www.egenix.com/company/contact/

**Comment by alexsavio** [comment]
Nice!
I'm using the talk list on the website scrapped on text files.

Maybe you find useful for showing the abstracts:
http://ipython.org/ipython-doc/2/api/generated/IPython.nbconvert.filters.markdown.html

**Comment by matrixise** [comment]
This issue is still open, is there a reason ?
