### ISSUE TITLE
Mixed content breaks web accounts for login

### ISSUE THREAD

**Issue by mgedmin** [EuroPython/epcon#156]
1. Log in
2. Go to your profile
3. Go to Login Options
4. Click Add Another Account

You get:
![screenshot](https://cloud.githubusercontent.com/assets/159967/8055743/764aabda-0eaa-11e5-92c1-726c216942a2.png)

and an error in the JS console:

> Mixed Content: The page at 'https://ep2015.europython.eu/accounts/profile/' was loaded over HTTPS, but requested an insecure resource 'http://ep2015.europython.eu/en/openid/embed?token_url=https%3A%2F%2Fep2015.europython.eu%2Faccounts%2Fjanrain%2Ftoken%2F&language_preference=en'. This request has been blocked; the content must be served over HTTPS.

My browser is Chromium 41.

**Comment by malemburg** [comment]
Thanks for reporting this. 

The OpenID functionality appears to be broken - even with https:// the URL does not exist and we also don't have Janrain account configured for the website.

**Comment by artcz** [comment]
I'll close this, because it's no longer relevant – we removed janrain completely and set up updated integration using only Google.
