### ISSUE TITLE
Only display accepted sessions in the scheduler

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#163]
At the moment, all sessions are shown, which makes selecting the right ones to put on the timetable more difficult than needed.

This change in conference/conference/admin.py would resolve this:

```
    def schedule_view_talks(self, conf):
        tids = []
        if conf.code == settings.CONFERENCE:
            results = utils.voting_results()
            if results is not None:
                tids = map(lambda x: x[0], results)
        complete = models.Talk.objects\
            .filter(conference=conf.code,
                    # Only display accepted sessions to shorten the
                    # the list and reduce the clutter
                    status='accepted')\
            .order_by('title')\
            .values_list('id', flat=True)
...
```

Problem here is that the conference app is a separate package which is difficult to upgrade.

**Comment by artcz** [comment]
I'll close this because it's out of date – the change mentioned was already implemented and the `conference` app is also part of the main epcon repo, not a separate repository like it was when this ticket was initially created.
