### ISSUE TITLE
Scheduler doesn't show the complete session list

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#164]
The list uses a fixed height, so is not shown on smaller screens.

Here's a fix for src/conference/conference/templates/admin/conference/conference/schedule_view_base.html which works in most cases:

```
#talks {
    width: 250px;
    position: fixed;
    height: 80%; /*700px;*/
    overflow: auto;
}
```

Since this is in the conference app package, it's difficult to apply, though.

**Comment by umgelurgel** [comment]
This hasn't been reported in the recent years, must have been resolved at some point.
