### ISSUE TITLE
We solve some issues, if you agree with our changes we can start using our conference library

### ISSUE THREAD

**Issue by oiertwo** [EuroPython/epcon#17]
Environment variable to limit maximum tickets (more spagethi code, but it WORKS!)
env name:
https://github.com/EuroPython/conference/blob/master/conference/settings.py#L31
and also the dates are important:
https://github.com/EuroPython/conference/blob/master/conference/models.py#L679

When submiting there was an issue with the birthday, if the user didnt set the birhtday the web sit crashed and the user couldt apply a proposal.

We solve with this (in conference app):
https://github.com/EuroPython/conference/blob/master/conference/forms.py#L185

If you agree with this emprovements just change from requirements the pythonItalia/conference and start using Europython/conference.

Cheers

**Comment by raulcd** [comment]
@oiertwo I am ok with it but the first one.
Why to use an environment variable. Just put the value of the `MAX_TICKETS` to the number we expect to have.

**Comment by oiertwo** [comment]
Its very simple configuration and takes in account all tickets, so we need to configure each time we need to open registration. So if we need to set the number each time, we also need to reinstall the library. This way for a docker-base deployment its easier to set up this number.

**Comment by fpliger** [comment]
Sorry... I don't get it.. is this a discussion proposal? otherwise it seems it should go into a PR...

**Comment by oiertwo** [comment]
i will do a proper pull request :), but it is too much work for a line :)

**Comment by artcz** [comment]
Closing because no longer relevant. :)
