### ISSUE TITLE
https://ep2015.europython.eu/accounts/profile/#account-spam-control doesn't switch to the tab

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#199]
I had expected the link on the tab to also cause the website to automatically switch to the tab.

Ionel mentioned on the EuroPython ML that this doesn't work and indeed it doesn't.

**Comment by matrixise** [comment]
maybe we could move this issue for ep2017

**Comment by umgelurgel** [comment]
That url no longer exists in ep2019, I'm going to close this ticket.
