### ISSUE TITLE
DoesNotExist at /accounts/profile/

### ISSUE THREAD

**Issue by barrachri** [EuroPython/epcon#2]
After using "login with google" you'll get an error.
Probably depending on

```
/Users/christianbarra/Dev/ep2015/src/assopy/assopy/views.py in profile
user = request.user.assopy_user 
```

**Comment by fpliger** [comment]
This is happening because assopy and conference profiles are not created when users login for the first time with their social auth.

Old code based on janrain is quite complex to understand with just a first glance. So I'll try to check if everything missing gets created and push a new PR.
