### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_tree_manager'

### ISSUE THREAD

**Issue by barrachri** [EuroPython/epcon#209]
Hi Marc,
after https://github.com/EuroPython/epcon/pull/206 I have this error: 

python manage.py run server: 
AttributeError: 'NoneType' object has no attribute '_tree_manager'

Last version of epcon used, the only difference is this: https://github.com/EuroPython/epcon/pull/208

**Comment by malemburg** [comment]
Sounds like a missing requirement. Here's the freeze from my installation:

BeautifulSoup==3.2.1
Django==1.5.11
Fabric==1.10.1
Pillow==2.6.0
PyJWT==0.4.1
Pygments==2.0.2
South==1.0.1
Unidecode==0.04.17
akismet==0.2.0
-e git+https://github.com/EuroPython/assopy.git@762837829a0caa12e467f04a4cee6ca1e25b64c6#egg=assopy-master
cmsplugin-filer==0.10.1
-e git+https://github.com/EuroPython/conference.git@87a922f196ecb281a87a4cc80fd83b89ae0830cb#egg=conference-master
django-appconf==1.0.1
django-authority==0.4
django-classy-tags==0.6.1
django-cms==3.0.6
django-crontab==0.4.2
django-filebrowser-no-grappelli==3.5.7
django-filer==0.9.8
django-markitup==2.2.2
django-mptt==0.6.1
django-page-cms==1.5.3
-e git://github.com/dcramer/django-paypal.git@4d58224317e9c0f4c9c2ee88bd1a6b8de8891800#egg=django_paypal-master
django-pingback==0.3
django-polymorphic==0.6.1
django-recaptcha-works==0.3.4
django-rosetta==0.7.4
django-sekizai==0.8.1
django-tagging==0.3.1
django-taggit==0.9.3
django-templatesadmin==0.7
django-xmlrpc==0.1.5
djangocms-admin-style==0.2.5
djangocms-grid==1.1
djangocms-text-ckeditor==2.4.1
easy-thumbnails==2.2
ecdsa==0.13
fancy-tag==0.2.0
gunicorn==19.2.1
-e git+https://github.com/pythonitalia/hcomments.git@4ec18851a377cc5ec6a59fe20dc561d77d476712#egg=hcomments-master
html2text==2015.2.18
html5lib==0.95
httplib2==0.9
lxml==3.4.2
markdown2==2.3.0
-e git+https://github.com/pythonitalia/microblog.git@201633c4fae5c859ed7d8a53480b82d9075e765f#egg=microblog-master
oauthlib==0.7.2
paramiko==1.15.2
polib==1.0.4
pycrypto==2.6.1
python-memcached==1.48
python-oembed==0.2.1
python-openid==2.2.5
python-social-auth==0.2.2
python-twitter==2.2
pytz==2014.10
raven==5.1.1
requests==2.5.3
requests-oauthlib==0.4.2
simplejson==3.6.5
six==1.9.0
stripe==1.19.1
suds==0.4

Could you check whether one of these is missing in your installation ?

**Comment by malemburg** [comment]
I checked the code: the ._tree_manager attribute is monkey patched into Django models by the package django-mptt.

**Comment by malemburg** [comment]
This is missing from the requirements.txt.

**Comment by barrachri** [comment]
So there is something wrong with the current https://github.com/EuroPython/epcon/blob/ep2016/requirements.txt

There are like half of your list there.

**Comment by malemburg** [comment]
That's well possible. The pip freeze output will also include packages that are pulled in as dependencies, so the repo requirements.txt doesn't need to list all packages, but it's certainly better style and safer to pin all versions.

**Comment by malemburg** [comment]
I've updated the requirements.txt file to my working set. Could you please try again with this one ?

**Comment by barrachri** [comment]
At least python manage.py run server is working....

**Comment by malemburg** [comment]
Using pipdeptree I created a dependency tree for the installed packages:

arning!!! Possible confusing dependencies found:
- django-cms==3.0.6 -> html5lib [installed: 0.95]
  django-page-cms==1.5.3 -> html5lib [required: ==0.95, installed: 0.95]
  djangocms-text-ckeditor==2.4.1 -> html5lib [installed: 0.95]
- requests-oauthlib==0.4.2 -> oauthlib [required: >=0.6.2, installed: 0.7.2]
  python-social-auth==0.2.2 -> oauthlib [required: >=0.3.8, installed: 0.7.2]
- django-appconf==1.0.1 -> six [installed: 1.9.0]
  python-social-auth==0.2.2 -> six [required: >=1.2.0, installed: 1.9.0]
  django-rosetta==0.7.4 -> six [required: >=1.2.0, installed: 1.9.0]
- cmsplugin-filer==0.10.1 -> django-sekizai [required: >=0.4.2, installed: 0.8.1]
  django-cms==3.0.6 -> django-sekizai [required: >=0.7, installed: 0.8.1]
- django-cms==3.0.6 -> django-classy-tags [required: >=0.5, installed: 0.6.1]
  django-sekizai==0.8.1 -> django-classy-tags [required: >=0.3.1, installed: 0.6.1]
- django-paypal==0.1.3 -> Django [required: >=1.4, installed: 1.5.11]
  easy-thumbnails==2.2 -> django [required: >=1.4.2, installed: 1.5.11]
  cmsplugin-filer==0.10.1 -> Django [required: >=1.4, installed: 1.5.11]
  django-cms==3.0.6 -> Django [required: >=1.4, installed: 1.5.11]
  django-filer==0.9.8 -> Django [required: >=1.4, installed: 1.5.11]
  django-classy-tags==0.6.1 -> Django [required: >1.3, installed: 1.5.11]
  fancy-tag==0.2.0 -> Django [required: >=1.0, installed: 1.5.11]
  django-rosetta==0.7.4 -> Django [required: >=1.3, installed: 1.5.11]
  django-mptt==0.6.1 -> Django [required: >=1.4.2, installed: 1.5.11]
- python-social-auth==0.2.2 -> requests-oauthlib [required: >=0.3.0, installed: 0.4.2]
  python-twitter==2.2 -> requests-oauthlib [installed: 0.4.2]
- hcomments==0.1.1 -> django-mptt [installed: 0.6.1]
  django-cms==3.0.6 -> django-mptt [required: ==0.5.2, installed: 0.6.1]
  django-filer==0.9.8 -> django-mptt [required: ==0.5.2, installed: 0.6.1]
- requests-oauthlib==0.4.2 -> requests [required: >=2.0.0, installed: 2.5.3]
  python-social-auth==0.2.2 -> requests [required: >=1.1.0, installed: 2.5.3]
  django-rosetta==0.7.4 -> requests [required: >=2.1.0, installed: 2.5.3]
  stripe==1.19.1 -> requests [required: >=0.8.8, installed: 2.5.3]
  python-twitter==2.2 -> requests [installed: 2.5.3]
- django-cms==3.0.6 -> south [required: >=0.7.2, installed: 1.0.1]
  django-page-cms==1.5.3 -> south [installed: 1.0.1]
  ------------------------------------------------------------------------
  django-crontab==0.4.2
  django-paypal==0.1.3
  - Django [required: >=1.4, installed: 1.5.11]
    hcomments==0.1.1
  - django-mptt [installed: 0.6.1]
    - Django [required: >=1.4.2, installed: 1.5.11]
  - django-recaptcha-works [installed: 0.3.4]
    django-tagging==0.3.1
    gunicorn==19.2.1
    akismet==0.2.0
    BeautifulSoup==3.2.1
    cmsplugin-filer==0.10.1
  - Django [required: >=1.4, installed: 1.5.11]
  - django-cms [required: >=3.0, installed: 3.0.6]
    - south [required: >=0.7.2, installed: 1.0.1]
    - html5lib [installed: 0.95]
    - django-sekizai [required: >=0.7, installed: 0.8.1]
      - django-classy-tags [required: >=0.3.1, installed: 0.6.1]
        - Django [required: >1.3, installed: 1.5.11]
    - django-classy-tags [required: >=0.5, installed: 0.6.1]
      - Django [required: >1.3, installed: 1.5.11]
    - django-mptt [required: ==0.5.2, installed: 0.6.1]
      - Django [required: >=1.4.2, installed: 1.5.11]
    - djangocms-admin-style [installed: 0.2.5]
    - Django [required: >=1.4, installed: 1.5.11]
  - django-sekizai [required: >=0.4.2, installed: 0.8.1]
    - django-classy-tags [required: >=0.3.1, installed: 0.6.1]
      - Django [required: >1.3, installed: 1.5.11]
  - easy-thumbnails [required: >=1.0, installed: 2.2]
    - django [required: >=1.4.2, installed: 1.5.11]
    - pillow [installed: 2.6.1]
  - django-filer [required: >=0.9, installed: 0.9.8]
    - Django [required: >=1.4, installed: 1.5.11]
    - easy-thumbnails [required: >=1.0, installed: 2.2]
      - django [required: >=1.4.2, installed: 1.5.11]
      - pillow [installed: 2.6.1]
    - django-mptt [required: ==0.5.2, installed: 0.6.1]
      - Django [required: >=1.4.2, installed: 1.5.11]
    - django-polymorphic [required: >=0.2, installed: 0.6.1]
      - setuptools
    - Unidecode [required: >=0.04, installed: 0.4.17]
  - django-appconf [installed: 1.0.1]
    - six [installed: 1.9.0]
      django-filebrowser-no-grappelli==3.5.7
      django-templatesadmin==0.7
      httplib2==0.9
      Pygments==2.0.2
      pytz==2015.7
      python-memcached==1.48
      python-oembed==0.2.1
      django-markitup==2.2.2
      python-social-auth==0.2.2
  - requests [required: >=1.1.0, installed: 2.5.3]
  - oauthlib [required: >=0.3.8, installed: 0.7.2]
  - six [required: >=1.2.0, installed: 1.9.0]
  - PyJWT [required: ==0.4.1, installed: 0.4.1]
  - python-openid [required: >=2.2, installed: 2.2.5]
  - requests-oauthlib [required: >=0.3.0, installed: 0.4.2]
    - oauthlib [required: >=0.6.2, installed: 0.7.2]
    - requests [required: >=2.0.0, installed: 2.5.3]
      django-page-cms==1.5.3
  - html5lib [required: ==0.95, installed: 0.95]
  - south [installed: 1.0.1]
    Fabric==1.10.1
  - paramiko [required: >=1.10, installed: 1.15.2]
    - pycrypto [required: >=2.1, installed: 2.6.1]
    - ecdsa [required: >=0.11, installed: 0.13]
      raven==5.1.1
      markdown2==2.3.0
      djangocms-grid==1.1
      django-rosetta==0.7.4
  - six [required: >=1.2.0, installed: 1.9.0]
  - Django [required: >=1.3, installed: 1.5.11]
  - requests [required: >=2.1.0, installed: 2.5.3]
  - polib [required: ==1.0.4, installed: 1.0.4]
    microblog==0.1.3
  - lxml [installed: 3.4.2]
  - django-pingback [installed: 0.3]
    - django-xmlrpc [required: >=0.1.0, installed: 0.1.5]
  - html2text [installed: 2015.2.18]
  - python-twitter [installed: 2.2]
    - requests-oauthlib [installed: 0.4.2]
      - oauthlib [required: >=0.6.2, installed: 0.7.2]
      - requests [required: >=2.0.0, installed: 2.5.3]
    - requests [installed: 2.5.3]
  - django-taggit [installed: 0.9.3]
  - fancy-tag [installed: 0.2.0]
    - Django [required: >=1.0, installed: 1.5.11]
      simplejson==3.6.5
      djangocms-text-ckeditor==2.4.1
  - Pillow [installed: 2.6.1]
  - html5lib [installed: 0.95]
  - django-cms [required: >=3.0, installed: 3.0.6]
    - south [required: >=0.7.2, installed: 1.0.1]
    - html5lib [installed: 0.95]
    - django-sekizai [required: >=0.7, installed: 0.8.1]
      - django-classy-tags [required: >=0.3.1, installed: 0.6.1]
        - Django [required: >1.3, installed: 1.5.11]
    - django-classy-tags [required: >=0.5, installed: 0.6.1]
      - Django [required: >1.3, installed: 1.5.11]
    - django-mptt [required: ==0.5.2, installed: 0.6.1]
      - Django [required: >=1.4.2, installed: 1.5.11]
    - djangocms-admin-style [installed: 0.2.5]
    - Django [required: >=1.4, installed: 1.5.11]
      stripe==1.19.1
  - requests [required: >=0.8.8, installed: 2.5.3]
    django-authority==0.4
    suds==0.4

It shows a few problems, but all dependencies are resolved. This one could need some attention, even though I don't think it has caused us any problems in the past:

  django-cms==3.0.6 -> django-mptt [required: ==0.5.2, installed: 0.6.1]
