### ISSUE TITLE
Prevent users from creating multiple accounts with the same email address

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#218]
This causes index problems in the system. The only way to make things work again is to delete one of the accounts.

**Comment by alexsavio** [comment]
RuntimeWarning: unique index on auth_user.email is missing, use: CREATE UNIQUE INDEX auth_user_unique_email ON auth_user(email COLLATE NOCASE)

**Comment by malemburg** [comment]
Yes, and it's not possible to add the index because there are indeed multiple entries with the same email address.

I suppose we should try to clean up the database and then add the index.

**Comment by alexsavio** [comment]
I would like to start with this cleanup. My plan is to do this, then help/wait for @patrick91 to do the upgrade. Once he is done the upgrade I would like to start merging `p3` into `conference`.

I will create a script to start cleaning up these users. I will start with the easy ones (not referenced by any other table).

**Comment by umgelurgel** [comment]
It's no longer possible to create an account if a user with the same email already exists.
