### ISSUE TITLE
Should we add 'EPS meeting' in TALK_ADMIN_TYPE?

### ISSUE THREAD

**Issue by alexsavio** [EuroPython/epcon#274]

**Comment by malemburg** [comment]
We could, but I don't have any idea what that TALK_ADMIN_TYPE is used for. Does it get marked in the schedule in some special way ?

**Comment by barrachri** [comment]
It was required by AlexH because there are some kind of talks that are not proposed with the cfp.

**Comment by alexsavio** [comment]
It is indeed a nice feature. This can be set up in each talk in the Talks section in the backend.
I guess 'EPS meeting' and 'Recruiting session' could be in TALK_ADMIN_TYPE as well. no?

**Comment by barrachri** [comment]
Program WG can put whatever there :+1:

**Comment by alexsavio** [comment]
Ok. I will check this with AlexH.

**Comment by malemburg** [comment]
Ok, but how is the field used in the system ?

It seems to be completely unused at the moment, since it's only defined on the model and not referenced anywhere else.

**Comment by alexsavio** [comment]
Check here: https://ep2016.europython.eu/admin/conference/talk/409/

**Comment by malemburg** [comment]
The talk doesn't use the field ?!

**Comment by alexsavio** [comment]
It is a marker for us for filtering talks for the schedule selection and the guidebook.

**Comment by malemburg** [comment]
If we do start using this field internally for program organization, we should at least add a column to the talk admin table and an appropriate filter.

**Comment by alexsavio** [comment]
The program organization and the guidebook are prepared outside the web system so I'm not sure what you propose is going to be used.

**Comment by malemburg** [comment]
Someone will have to enter these fields, right ? This will be a bit difficult to manage without seeing them in the admin interface. I can add this, no problem.

BTW: I've been doing the Guidebook stuff last year and didn't need such a field.

Anyway, let's add "EPS session" to the list and any other talk type which won't be going into talk voting. We'll then have to update the talk voting machinery to not include these talks.

**Comment by alexsavio** [comment]
Thanks.
I have added 'EPS session' and 'Recruiting session' in the models.py file. I can push it, should I?

**Comment by malemburg** [comment]
Where's the PR ?

**Comment by alexsavio** [comment]
Forget it. I tried to push to epcon, but seeing I didn't have access, messed it all up. I am trying to find my code now.

**Comment by alexsavio** [comment]
Found it. I will do it, just a moment.

**Comment by alexsavio** [comment]
I can't do it now. There is something wrong in the ACPySS fork. My git knowledge is useless when it starts crashing.

**Comment by malemburg** [comment]
https://github.com/EuroPython/epcon/commit/8e2ba262731aedc2048f7d21208ac47c4451aced
