### ISSUE TITLE
Some users give a error 500 when trying to doppelgang her/him

### ISSUE THREAD

**Issue by alexsavio** [EuroPython/epcon#283]
For example this user:
https://ep2016.europython.eu/admin/auth/user/2005/login/

He/she got a ticket from:
https://ep2016.europython.eu/admin/auth/user/2000/
I think this might be the issue, I remember we had a fix for this from last year but can't figure it out now.

The same might be happening with the owners or receivers of owners of the following tickets:
ERROR:root:Could not find a profile for ticket_id 2079.
ERROR:root:Could not find a profile for ticket_id 2223.
ERROR:root:Could not find a profile for ticket_id 2262.
ERROR:root:Could not find a profile for ticket_id 2290.

The ticket_id 2079 is the one I described above.

**Comment by alexsavio** [comment]
For the case of the ticket_id 2223.

Exactly the same happens to:
https://ep2016.europython.eu/admin/auth/user/2110/login/

Who received a ticket from:
https://ep2016.europython.eu/admin/auth/user/2109/

**Comment by alexsavio** [comment]
I am using the command:
`python manage.py ticket_profiles ep2016 --ticket-id 2223 --raise`

available in this branch:
https://github.com/PythonSanSebastian/epcon/tree/alxfix

**Comment by malemburg** [comment]
This is the traceback we're getting from the system:

```
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 202, in inner
    return view(request, *args, **kwargs)

  File "/usr/src/ep2016/assopy/admin.py", line 388, in create_doppelganger
    auth.login(request, user)

  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 93, in login
    request.session[BACKEND_SESSION_KEY] = user.backend

AttributeError: 'AnonymousUser' object has no attribute 'backend'
```

**Comment by malemburg** [comment]
These are user records created by the system when someone assigns a ticket to an email address for which there is no existing user record in the system. Apparently, the system doesn't also create a profile object for the user.
