### ISSUE TITLE
Website installation fails with DatabaseError: no such table: conference_talk

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#31]
I followed the instructions from the README.md, but then get this output from migrate (after a syncdb run):

europython-2015/epcon> python manage.py migrate
/home/lemburg/egenix/projects/europython-2015/epcon/src/assopy/assopy/utils.py:61: RuntimeWarning: unique index on auth_user.email is missing, use: CREATE UNIQUE INDEX auth_user_unique_email ON auth_user(email COLLATE NOCASE);
  warnings.warn(msg, RuntimeWarning)

Running migrations for p3:
- Migrating forwards to 0010_auto__chg_field_hotelroom_booking.
  > p3:0003_p3talks
- Migration 'p3:0003_p3talks' is marked for no-dry-run.
  ! Error found during real run of migration! Aborting.
  
  ! Since you have a database that does not support running
  ! schema-altering statements in transactions, we have had
  ! to leave it in an interim state between migrations.

! You _might_ be able to recover with:   (migration cannot be dry-run; cannot discover commands)
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: p3:0003_p3talks
DatabaseError: no such table: conference_talk

**Comment by malemburg** [comment]
For now, I simply copied the p3.db from the website, but the above is a bummer for anyone who wants to work on the website.

**Comment by aramboi** [comment]
This solved in the current dev branch `dev/2020`. Closing.
