### ISSUE TITLE
Level not displayed on talk detail page

### ISSUE THREAD

**Issue by blueyed** [EuroPython/epcon#322]
The talk / voting list (https://ep2016.europython.eu/conference/voting/) displays "… for Beginner", but this information is missing on the detail page: https://ep2016.europython.eu/conference/talks/restful-api-best-practises

**Comment by umgelurgel** [comment]
Thanks for reporting this! looks like this has been fixed since (e.g. looking at https://ep2019.europython.eu/talks/eDRygAF-kubernetes-101-for-python-developers/), resolving.
