### ISSUE TITLE
"chat with us" link on voting page does not work

### ISSUE THREAD

**Issue by blueyed** [EuroPython/epcon#323]
With the "Need more info?" box on https://ep2016.europython.eu/conference/voting/ there's a link "chat with us", containing this code:

> habla_window.show(); habla_window.expand()

Clicking it causes this error however:

> ReferenceError: habla_window is not defined

**Comment by blueyed** [comment]
Seems to have been removed in bc759e7f97ddc6c7174970f49f9b9263f1e86f04 / 1179376a38bb0f41329ab42228dfc7589bca0e9c.

**Comment by umgelurgel** [comment]
Thanks for reporting this - the `chat with us` functionality has been removed from the recent versions of the website, going to close this ticket.
