### ISSUE TITLE
Filter out the not-accepted talks in the list in the schedule view

### ISSUE THREAD

**Issue by alexsavio** [EuroPython/epcon#328]
We are building the schedule, it would be really nice to have only the 'accepted' talks in the list view on this page:
https://ep2016.europython.eu/admin/conference/conference/ep2016/schedule/

**Comment by alexsavio** [comment]
...and add the admin talks :)
please

**Comment by malemburg** [comment]
What are "admin talks" ?

I can have a look, but this part of the system is really really messy :-(

**Comment by malemburg** [comment]
Do you have an example of a talk that was not accepted, but is shown in the list ?

I'm asking because from looking at the code, only accepted talks should be shown in the listing.

**Comment by malemburg** [comment]
Ok, found one.. one of the talks I had submitted.

**Comment by alexsavio** [comment]
The total number of talks in the list should help. We have ~300 submitted talks and ~100 should be accepted.

**Comment by malemburg** [comment]
The total shown is 169 sessions. Sounds about right :-)

**Comment by alexsavio** [comment]
Thanks Marc, I will check it.

**Comment by malemburg** [comment]
The fix itself was trivial... but finding the right location for the fix took more than an hour.

i still don't know what "admin talks" are, so don't know whether this addresses everything you wanted.

**Comment by alexsavio** [comment]
There were some talks added by @alanderex like the Closing Session: https://ep2016.europython.eu/admin/conference/talk/699/
As it is 'accepted', it appears in the list. I am not sure if we will need more fixes here, but I think this is fine. Thanks!
