### ISSUE TITLE
Adjust RPXNOW app ID

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#34]
This is in ./p3/templates/p3/base.html

I have no idea what it's used for.

**Comment by malemburg** [comment]
It seems that RPXNOW has something to do with OpenID:

https://rpxnow.com/docs/providers
http://blog.nerdbank.net/2009/01/why-using-rpxnow-is-bad-idea.html

We don't have an account with them, so I doubt this even works.

**Comment by barrachri** [comment]
Btw I think that we aren't using Janrain anymore.

2015-02-27 16:15 GMT+01:00 Marc-Andre Lemburg notifications@github.com:

> It seems that RPXNOW has something to do with OpenID:
> 
> https://rpxnow.com/docs/providers
> http://blog.nerdbank.net/2009/01/why-using-rpxnow-is-bad-idea.html
> 
> We don't have an account with them, so I doubt this even works.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EuroPython/epcon/issues/34#issuecomment-76409757.

## 

Best,
Christian
