### ISSUE TITLE
Activation link email not sent by EuroPython 2016

### ISSUE THREAD

**Issue by lmotta-288939** [EuroPython/epcon#345]
I've created my account at EuroPython website, but I didn't received any email notification about account activation. I try to connect using my recent account, but a message is showed:

```
ACTIVATION REQUIRED
Luis Antonio Jacob da your account is created, you need to activate it following the instruction sent to you by email at luis.motta@embraer.com.br
```

So, what I have to do in this case?

Thanks in advance.

**Comment by europython-society** [comment]
On 05.05.2016 22:23, lmotta-288939 wrote:

> I've created my account at EuroPython website, but I didn't received any email notification about account activation. I try to connect using my recent account, but a message is showed:
> 
> ```
>   ACTIVATION REQUIRED
>   Luis Antonio Jacob da your account is created, you need to activate it following the instruction sent to you by email at luis.motta@embraer.com.br
> ```
> 
>   So, what I have to do in this case?

Have you checked your spam folder ? In some cases, the verification
emails get flagged as possible spam.

I've now manually enabled the account, so you should be able to
log in.

## 

Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by lmotta-288939** [comment]
Hello, Marc.

```
    There is no EuroPyton email on my spam list. After your [manual] 
```

validation, now I can access my account.
        Thank you very much.

My Best Regards.

Luís Antonio Jacob da Motta (Jacob) 
EMBRAER S.A. 
Product Development Engineer 
Phone: +55(16) 3338-9079 
Fax: +55(12) 3927-6600 - ramal 0304 
www.embraer.com.br 

Cell 283 - Flight Test Instrumentation Engineering 
Quality Clinic: click here to contact us
