### ISSUE TITLE
EuroPython 2016 emails not received (and no, it's not on my spam list)

### ISSUE THREAD

**Issue by lmotta-288939** [EuroPython/epcon#346]
I've created my account and I haven't received the confirmation email. So I opened an issue (#345) and Mr Marc-Andre Lemburg manually enabled my account.

After that I tried to change my password and I haven't receive any email about it, again. So I think there is some problem with my email address at EuroPython 2016 system. Just to validate my suggestion, I've created another account using my personal email address and the emails were received successfully.

But my ticket shall be purchased using my company email address (luis.motta@embraer.com.br). Is possible to verify is is any error there when you try to send me any email?

Thanks. :D

**Comment by alexsavio** [comment]
This problem is happening to more people.

**Comment by lmotta-288939** [comment]
Thanks for the information, @alexsavio . Anyway, I did my registration for EuroPython 2016 and I downloaded my sheet confirmation on conference's page. I'll see you there. :)

My Best Regards.

**Comment by malemburg** [comment]
I checked the mail logs and found that AOL is currently blocking our server. Apart from that I could not find any hints for email problems.

**Comment by lmotta-288939** [comment]
Ok, @malemburg. Thank you for your help. :D
