### ISSUE TITLE
Add new talk status "canceled" for canceled talks

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#365]
This would help with the organization of talks.

**Comment by malemburg** [comment]
This is not working yet. The schedule gives a traceback with the PR.

**Comment by malemburg** [comment]
The implementation still is not complete as there are several other places in the code that assume just "accepted" and "proposed" as status.

**Comment by malemburg** [comment]
"Canceled" talks are still visible on the website - unlike "proposed" talks, which are not, unless you log in and have proper rights (outside the talk voting period).

This needs to be fixed as well.

**Comment by matrixise** [comment]
@malemburg on which page, url ? thanks

**Comment by umgelurgel** [comment]
This ticket looks to be outdated, going to close.
