### ISSUE TITLE
Configuring tickets to 4XL t-shirts doesn't work

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#377]
See https://helpdesk.europython.eu/tickets/5672/ for the description of the error. Essentially, it is not possible to save a ticket configured for 4XL t-shirts.

**Comment by alexsavio** [comment]
The 3XL (female) neither.
https://helpdesk.europython.eu/tickets/5783/

**Comment by alexsavio** [comment]
It seems the html view can't save the new sizes we added in 2015 in the backend. From the backend it is possible to configure the correct size, but not from the frontend.
