### ISSUE TITLE
Can't send email to speakers only.

### ISSUE THREAD

**Issue by alexsavio** [EuroPython/epcon#392]
Would be nice to be able to send emails to speakers only.

**Comment by malemburg** [comment]
This is already possible: https://ep2016.europython.eu/admin/conference/conference/ep2016/stats/details?code=conference_speakers.accepted_speakers

More options are available on this page: https://ep2016.europython.eu/admin/conference/conference/ep2016/stats/

**Comment by alexsavio** [comment]
Ok, I couldn't find it. Thanks! I will have a look.
