### ISSUE TITLE
Do we really need to create an HotelBooking instance for a conference?

### ISSUE THREAD

**Issue by patrick91** [EuroPython/epcon#407]
https://github.com/EuroPython/epcon/blob/dev/ep2017/p3/forms.py#L549

maybe we need a better way to create automatically the needed stuff when creating a new conference :)

**Comment by malemburg** [comment]
We aren't using hotel bookings anymore, so don't need any of this anymore. Feel free to rip it out.

**Comment by umgelurgel** [comment]
The `HotelBooking` model has been removed.
