### ISSUE TITLE
Move info message in a better place

### ISSUE THREAD

**Issue by patrick91** [EuroPython/epcon#408]
<img width="637" alt="screen shot 2016-11-06 at 11 06 14" src="https://cloud.githubusercontent.com/assets/667029/20036743/21266344-a411-11e6-8873-a04c4f70e551.png">

**Comment by malemburg** [comment]
Indeed. The same goes for error messages, which people sometimes don't see because there is not obvious "Submission failed due to errors" message shown anywhere, only per field error messages which are not easy to spot due to the long form.

**Comment by umgelurgel** [comment]
This has been fixed in the ep2019 templates.
