### ISSUE TITLE
Automate setup

### ISSUE THREAD

**Issue by patrick91** [EuroPython/epcon#413]
In order to have more contributor to the code base we should try to facilitate the contribution process, first of all we should automate the setup process. The readme has some instructions:

> The first thing you need to do is add 4 pages with the following ids:
> 
> HOME (advanced settings->id:home)
> CONTACTS (advanced settings->id:contacts, template: content)
> PRIVACY (advanced settings->id:privacy, template: content page, single column)
> CONDUCT-CODE (advanced settings->id:conduct-code)
> If you don't do that you'll start to see some errors like broken url reference. NOTE: You may need to restart the server after adding the pages to let the system detect them.
> 
> Next, you will have to create a conference record under /admin/conference/conference/. The links on this conference record also allow setting up the schedule and checking attendee statistics.
> 
> The shopping cart system has support for hotel bookings. In order to get the cart working without errors, you have to create a conference record under /admin/p3/hotelbooking/.

We can probably automate all of these stuff, I was thinking to add a management command for doing so. Comments?

**Comment by alexsavio** [comment]
I think that any help/improvement on the launch of epcon is welcome.
Maybe a separate project that creates a docker container running epcon from the source code in the repository?

**Comment by malemburg** [comment]
Should the above be done during database setup via fixtures ?

**Comment by patrick91** [comment]
@alexsavio we can add a dockerfile to this repo, no need to create another repo :) 
@malemburg not sure, a management command is more flexible (eg, we can ask the user the conference name OR code)

**Comment by malemburg** [comment]
For getting an initial working system, it's fine to have some default objects created via fixtures. The user can easily change those as needed afterwards, but at least the system will startup after running the initial installation.

I'm not sure whether we should add a docker container as default test run time environment. Using this is a lot more difficult than simply firing up a virtualenv. Besides, we already do have a docker setup - the one we're using to run our server :-)

**Comment by malemburg** [comment]
Adding a management command is possible as well, but you'd then have an extra manual step for initializing the system. No strong opinion, either way, though. The only thing that's important is to have users get a running system which doesn't startup with cryptic error messages.

**Comment by LuRsT** [comment]
I'm just setting up this repo and I got in trouble with those first steps since after creating the HOME page, I get redirected to an unknown page and I cannot seem to create any more new pages as per the instructions, so I'm a bit stuck. I'm new to Django CMS, once I figure this out, I'll try to update the documentation, but this should definitely be put in a script at least.

**Comment by artcz** [comment]
I didn't notice this issue and created #572 and fixed it on ep2017 sprints.

**Comment by patrick91** [comment]
Fixed with #575
