### ISSUE TITLE
Don't use DEFAULT_URL_PREFIX when request is available or can be provided

### ISSUE THREAD

**Issue by patrick91** [EuroPython/epcon#414]
It is a bit annoying to change `DEFAULT_URL_PREFIX` when developing, so when we can use the request (request.create_absolute_uri) we should do so :)

**Comment by malemburg** [comment]
Note that you can tweak the settings in pycon/settings_locale.py (sic) for dev purposes.

**Comment by artcz** [comment]
Closing because looks like no longer relevant due to dev settings.
