### ISSUE TITLE
Enable cms template tags processor back

### ISSUE THREAD

**Issue by patrick91** [EuroPython/epcon#420]

**Comment by malemburg** [comment]
See https://github.com/EuroPython/epcon/pull/404/commits/10b0e58d8c2c59d9f8062338637b476f6d485445

**Comment by malemburg** [comment]
We will probably need this back again, since the CMS pages do use templating as well (e.g. for the registration and talk submission pages).

**Comment by malemburg** [comment]
This may be related to #426
