### ISSUE TITLE
Saving Stripe charge.id

### ISSUE THREAD

**Issue by barrachri** [EuroPython/epcon#424]
Currently, we don't save the Stripe charge.id.

This would (at least in my mind) simplify the refund process.

This is where the charge is actually made:
https://github.com/EuroPython/epcon/blob/ep2017/assopy/stripe/views.py#L85

'charge.id' is what we need to save in the db.

Basically I think we should add a new field here: https://github.com/EuroPython/epcon/blob/ep2017/assopy/models.py#L553

and put the value of `charge.id` inside of it

Some resources:
 * Stripe API: https://stripe.com/docs/api
 * Python API docs: https://stripe.com/docs/api/python
 * CC card charge docs: https://stripe.com/docs/api/python#charges
 * Official Stripe module we're using: https://pypi.python.org/pypi/stripe/
 * Our stripe integration is in https://github.com/EuroPython/epcon/blob/ep2017/assopy/stripe/

We're using  a fairly old version of the stripe module: 1.19.1; perhaps we ought to upgrade.

**Comment by malemburg** [comment]
Fixed in #436
