### ISSUE TITLE
Add dynamic table of contents JS to "Content page" CMS template

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#428]
For ep2016, we had a dynamic generation of a TOC on most pages. I added them there by hand, e.g. 

https://ep2016.europython.eu/en/sponsor/information/

For ep2017, it would be better to add this directly to the CMS template, and then use a different template, in case the TOC should not be shown.

**Comment by patrick91** [comment]
Would something like this be helpful? https://github.com/nghuuphuoc/tocjs

**Comment by malemburg** [comment]
We could also use tocjs. What I wrote is a lot smaller, though:

https://github.com/EuroPython/epcon/blob/ep2017/p3/static/p6/javascripts/utils.js#L735
