### ISSUE TITLE
Disable features that aren't ready yet

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#43]
These things are currently listed on the website, but not yet ready for production:
- calendar
- CFP
- newsletter box

(possibly more, once you are logged in)

**Comment by malemburg** [comment]
Removed calendar and CFP from the menu (but did not unpublish them).

**Comment by barrachri** [comment]
Why calendar ?

I think it's useful to have some information about some deadlines (tickets
and cfp).

2015-02-27 18:45 GMT+01:00 Marc-Andre Lemburg notifications@github.com:

> Removed calendar and CFP from the menu (but did not unpublish them).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EuroPython/epcon/issues/43#issuecomment-76438858.

## 

Best,
Christian

**Comment by malemburg** [comment]
Because we don't have those dates finalized yet.

**Comment by barrachri** [comment]
ok :)

2015-02-27 19:19 GMT+01:00 Marc-Andre Lemburg notifications@github.com:

> Because we don't have those dates finalized yet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EuroPython/epcon/issues/43#issuecomment-76444379.

## 

Best,
Christian

**Comment by malemburg** [comment]
Disabled the newsletter box in #49.

**Comment by malemburg** [comment]
Done.
