### ISSUE TITLE
Fix the CSS for ep2017

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#440]
The move to the new CMS version seems to have broken a lot of CSS on the website, e.g. bullet lists no longer format correctly:

https://dev.europython.eu/en/europython/social-media/

and spacing seems broken as well.

**Comment by patrick91** [comment]
Looks good to me! Can you send a screenshot and the browser info?

**Comment by malemburg** [comment]
![sponsorship packages europython 2017 rimini 9-16 july 2017-2017-03-03 23_09_00](https://cloud.githubusercontent.com/assets/6735498/23570916/c5530736-0066-11e7-8902-3c3ff7aee76a.png)

**Comment by malemburg** [comment]
This is on Firefox.

**Comment by malemburg** [comment]
And this page: https://dev.europython.eu/en/sponsor/packages/
