### ISSUE TITLE
Sign in issues

### ISSUE THREAD

**Issue by diegorusso** [EuroPython/epcon#472]
I'm not able to login on the website at all. I have an existent profile because if I try to sign up, it will say "email already used",

"Login with Google" is broken: I have an error 400 from Google: redirect_uri_mismatch

"Recover the password": I'm not receiving any email to recover the password

Cheers

**Comment by diegorusso** [comment]
Login with Google has been fixed

**Comment by patrick91** [comment]
Fixed in #476
