### ISSUE TITLE
Bad link to "call for proposals"

### ISSUE THREAD

**Issue by aleaxit** [EuroPython/epcon#478]
The link to "call for proposals" on page https://ep2017.europython.eu/en/ is https://ep2017.europython.eu/en/ (the same page where the link lives!) so clicking it does nothing; the true link would be https://ep2017.europython.eu/en/call-for-proposals/ (I only know that because I got it in an email!).  Easy to fix, of course, just trivial editing:-).

**Comment by malemburg** [comment]
Hi Alex, thanks for reporting the problem. It's fixed now.
