### ISSUE TITLE
Some abstracts are not editable 

### ISSUE THREAD

**Issue by alanderex** [EuroPython/epcon#482]
@EuroPython/webwg 
We received some reports that the speakers are not able to edit the submissions.
see e.g. helpdesk:
https://helpdesk.europython.eu/tickets/20422/

**Comment by alanderex** [comment]
To avoid tickets on the help desk we need the talks to be editable again please. 
Trainers need to add info on the trainings as well as improvements are allowed.

**Comment by umgelurgel** [comment]
Should there be a cutoff date when the talks/trainings stop being editable again (e.g. when the conference starts)? Are there any other fields that should be made editable apart from the abstract - such as tags, pyhon level requirements, domain level requiements? I'd assume the title/sub title shouldn't be modifiable - could you confirm that should be the case @alanderex ?

**Comment by alanderex** [comment]
@umgelurgel Good points but I think everything should be editable until the end of the conference, after the conference no more edits. We do have a  Jupiter notebook for monitoring changes. We did not see any misuse in the past.

**Comment by umgelurgel** [comment]
Thanks for the clarification, @alanderex ! Just to confirm I've understood correctly then - the speaker should be able to edit all talk details, apart from the talk type (workshop, 30 min talk, 45 min talk etc), until the end of the conference - is that correct?

**Comment by alanderex** [comment]
yes confirmed! Thanks!

**Comment by umgelurgel** [comment]
Merged and deployed to production.
