### ISSUE TITLE
Talk voting should be possible for all attendees with tickets

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#498]
Unlike in the past, we will also allow attendees of EP2015 and EP2016 to vote.

**Comment by malemburg** [comment]
It seems that we only need to change this in settings.py:

def CONFERENCE_VOTING_ALLOWED(user):

    """ Determine whether user is allowed to participate in talk voting.

    """
    if not user.is_authenticated():
        return False
    if user.is_superuser:
        return True

    # Speakers of the current conference are always allowed to vote
    from p3.models import TalkSpeaker, Speaker
    try:
        count = TalkSpeaker.objects.filter(
            talk__conference=CONFERENCE_CONFERENCE,
            speaker=user.speaker).count()
    except Speaker.DoesNotExist:
        pass
    else:
        if count > 0:
            return True

    # People who have a ticket for the current conference assigned to
    # them can vote
    from p3 import models
    # Starting with EP2017, we know that all assigned tickets have
    # .assigned_to set correctly
    tickets = models.TicketConference.objects \
              .filter(ticket__fare__conference=CONFERENCE_CONFERENCE,
                      assigned_to=user.email)

by removing the ticket__fare__conference=CONFERENCE_CONFERENCE query.

**Comment by alanderex** [comment]
I guess we can close this one now, can't we

**Comment by malemburg** [comment]
Yes, it worked as intended.
