### ISSUE TITLE
Schedule: support for 5 minute breaks  

### ISSUE THREAD

**Issue by alanderex** [EuroPython/epcon#510]
We want to add 5 minute breaks between the talks, so people have more time to change rooms between talks.

- [Schedule display ] 
https://ep2016.europython.eu/p3/schedule/ep2016/
Please add a CSS class to support **5 minute** granularity (currently 15 minutes granularity is supported).
_For example in the morning:_
_current state.                desired state_
10:30 talk No. 1            10:30 talk  No. 1
(n/a)                               5 min break
11:00 talk  No. 2           11:05 talk  No. 2
(n/a)                               5 min break
11:30 talk  No. 3           10:30 talk  No. 3
(n/a)                               5 min break

- [Schedule planning ] 
The planning app in the backend should allow 5 minute granularity as well, though we'd wan work with 15 minute granularity here and move the talks e.g. via an SQL statement directly. This is just nice to have.

**Comment by malemburg** [comment]
I discussed this with Patrick and we think it won't really look good on the website.

**Comment by alanderex** [comment]
We need this for good reasons, let's not die in vain ;)

**Comment by patrick91** [comment]
Done in #552 should look like this: http://s.patrick.wtf/0UIhOz56IZ

**Comment by patrick91** [comment]
Let me know if that doesn't work
