### ISSUE TITLE
Talk voting 

### ISSUE THREAD

**Issue by alanderex** [EuroPython/epcon#512]
We go the following feedback from a user, see below.
I tested in Chrome either and tags cannot be selected in Chrome, the filter doesn't work.

--

> * keyword search doesn't appear to work
> * there are some errors in console:
> 
> 2?abstracts=all&talk_type=all&language=all&order=random&tags=asyncio&_pushed=1:28812
> A Parser-blocking, cross site (i.e. different eTLD+1) script,
> https://rpxnow.com/js/lib/rpx.js, is invoked via document.write. The
> network request for this script MAY be blocked by the browser in this
> or a future page load due to poor network connectivity. If blocked in
> this page load, it will be confirmed in a subsequent console
> message.See https://www.chromestatus.com/feature/5718547946799104 for
> more details.
> (anonymous) @ ?abstracts=all&talk_type=all&language=all&order=random&tags=asyncio&_pushed=1:28812
> util.js:219 Google Maps API warning: NoApiKeys
> https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
> tB.j @ util.js:219
> (anonymous) @ js?sensor=false:131
> (anonymous) @ js?sensor=false:53
> (anonymous) @ js?sensor=false:50
> (anonymous) @ js?sensor=false:53
> (anonymous) @ js?sensor=false:104
> (anonymous) @ js?sensor=false:50
> (anonymous) @ js?sensor=false:104
> (anonymous) @ js?sensor=false:50
> (anonymous) @ js?sensor=false:104
> Sc @ js?sensor=false:52
> Rc.eb @ js?sensor=false:104
> (anonymous) @ util.js:1
> util.js:219 Google Maps API warning: SensorNotRequired
> https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
> 
> Why would there be a google maps API call in the first place?

**Comment by patrick91** [comment]
Google maps is probably loaded in all the pages, even if it is used in just one place :)

I'll have a look at the filtering issue tonight or tomorrow

**Comment by alanderex** [comment]
Superb, thanks :)
