### ISSUE TITLE
Misspelling of Accommodation 

### ISSUE THREAD

**Issue by rgaiacs** [EuroPython/epcon#544]
https://ep2017.europython.eu/en/location/accomodation/ should be https://ep2017.europython.eu/en/location/accommodation/ and "Accomodation" replaced by "Accommodation" on the page as illustrated on the screenshot.

![screenshot_2017-06-02_15-30-29](https://cloud.githubusercontent.com/assets/1506457/26730491/08d6ab46-47a9-11e7-9428-308ab0a41558.png)

Similar fix should be done on the navigation bar.

**Thanks to make a great conference.**

**Comment by LuRsT** [comment]
@rgaiacs Thanks for spotting! Will fix!

**Comment by LuRsT** [comment]
:boom: Done :boom:
