### ISSUE TITLE
ep2016 site login

### ISSUE THREAD

**Issue by alanderex** [EuroPython/epcon#546]
Login on the ep2016 site returns a 404 I think this is confusion, shouldn't we better redirect to the current EP site? I think it's not obvious the page is static for outsiders…

**Comment by malemburg** [comment]
It was just a quick way to turn off logins. We can fix this after the EP2017 conference.

**Comment by alanderex** [comment]
Yes, it's just a minor issue

**Comment by umgelurgel** [comment]
Don't think this is an issue anymore.
