### ISSUE TITLE
Speaker profiles are no longer automatically turned public

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#551]
There is a listener in charge of doing this, which triggers whenever a talk is edited, but this doesn't appear to work anymore after the upgrade to Django 1.8.

We're now working around this by setting the flag directly in the database, but it's not a good solution.

**Comment by malemburg** [comment]
Looks like this bug is still pending. We've run into the same situation for EP2019.

**Comment by umgelurgel** [comment]
This gets fixed in #992 - the profile visibility setting is ignored if the user has an accepted talk for the current conference; I'll make a note about it in the form when updating users profile/settings in #989 , too.

Resolving, please re-open if you think there's more to be done.

**Comment by malemburg** [comment]
Please undo this and continue relying on the profile visibility setting.

We need to fix the cause, not work-around the issue.

**Comment by umgelurgel** [comment]
This was fixed in ep2019 - this was not a workaround, the functionality from ep2018 was maintained, closing.
