### ISSUE TITLE
Reduce the number of django deprecation Warnings

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#576]
There's some code that generates deprecation warnings like this:

```
/home/a/P/europython/artcz/epcon/hcomments/models.py:35: RemovedInDjango19Warning: Model class hcomments.models.ThreadSubscription doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
```
or `assopy.Vat.fares: (fields.W340) null has no effect on ManyToManyField`

that appear during runserver.

We need to update it, in order to update to newer versions of django. (and also reduce the noise on the runserver output, especially on startup)

**Comment by sparkiegeek** [comment]
@artcz can I pick this up or are you actively working on it?

**Comment by umgelurgel** [comment]
This was (mostly) fixed across multiple PRs.
