### ISSUE TITLE
Invoices should only be created once and stored in the backend

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#591]
The current system recreates the invoices on demand, which can have strange effects, e.g. causing invoices for other conference years use different issuers. This is not correct accounting and needs to be fixed going forward.

The system should create invoices only once and then store them in the database as JSON or text field.

The next time a user requests the invoice, the stored invoice should be returned.

**Comment by artcz** [comment]
Created a WIP PR for this at #596

**Comment by artcz** [comment]
PR mentioned above was merged so I guess this one is more or less solved.
