### ISSUE TITLE
Clean up static files situation.

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#613]
Basically we have the same issue as previously with templates – instead of a single global location we have different `static/` subfolders inside apps.

We should probably do the same thing we did with templates and put them all in a single location.
(also, maybe delete unused javascript/css files too)

**Comment by artcz** [comment]
Update: This was basically done with move to 2019 bootstrap template structure, should be relatively easy to remove the old static files now.

**Comment by umgelurgel** [comment]
This should be done now - thanks to the work by @artcz last year, it was pretty straightforward to remove all unused templates and associated static files.
