### ISSUE TITLE
Need to show and record UK VAT for all invoices in 2018

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#617]
Since VAT on conference tickets has to be charged in the country where the conference takes place, we will have to charge 20% UK VAT on tickets for EuroPython 2018. Going forward, we'll have to do the same for other countries.

This introduces a few challenges.

These are the invoice requirements for the UK:

 - General requirements for invoices: https://www.gov.uk/invoicing-and-taking-payment-from-customers/invoices-what-they-must-include
 - More requirements for VAT invoices: https://www.gov.uk/vat-record-keeping/vat-invoices

The second page mentions this important detail: "you must: show the total VAT payable in sterling on your VAT invoice if the supply takes place in the UK". Further down on the page it lists the officially allowed sources for exchange rates (FX rates).

After some research it's probably best to use this combination:

 - Python package forex-python: https://github.com/MicroPyramid/forex-python
 - Interface to ECB rates: http://fixer.io/
 - ECB rates: https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

or go with a very light weight approach such as this direct interface to the ECB:

- https://myridia.com/dev_posts/view/1955

In any case, the conversion tool must cache the exchange rate and use the cached rate in case the FX source fails for some reason. We may also need to have a config variable to a default exchange rate in case all fails.

Apart from the VAT total in GBP requirement, I believe we already cover all the other requirements from the above lists.

For VAT submission purposes, it is important to not only show the VAT in GBP on the invoices, but also record this in the database, since the field will need to serve as basis for the total amount to submit.

Furthermore, I believe this requirements (and probably more) will pop up in the future as well, so it's probably good to add not only a local_vat float field, but also a local_vat_currency text field holding the ISO3 name of the currency in question (GBP for EuroPython 2018) and a config variable to set the local currency.

**Comment by artcz** [comment]
This was implemented, and the 2018 conference is already closed. For future editions we always need to make sure (and possibly update) if we're compliant with local regulations.
