### ISSUE TITLE
Invoices have to be enhanced to meet UK standards

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#620]
I checked this against the requirements. We're missing these parts:

1. contact information (email address, website)
2. time of supply - normally just a sentence: "Unless otherwise indicated, time of supply corresponds to the invoice date."
3. Price per item, excluding VAT
(4. VAT rate for each item)

The last one I'm not sure about since we'll normally just have one rate per invoice, but probably can't hurt. We can also simply add these per item infos to the description text (to not to break the layout).

**Comment by artcz** [comment]
Closed because fixed already + no longer relevant – for 2019 we need to meet Swiss standards. :)
