### ISSUE TITLE
Some pages still reference Rimini

### ISSUE THREAD

**Issue by GadgetSteve** [EuroPython/epcon#642]
I have noticed that in at least a couple of places Rimini is still referenced:

- https://ep2018.europython.eu/en/registration/tips-for-attendees/ has:
  - If you want to save on roaming charges, you may want to get a prepaid SIM card for the time you are in **Rimini**. We cannot offer SIM cards for sale ourselves due to the local regulations, but you can get SIM cards at local shops in **Rimini** without much problem, provided you bring an ID card for the registration. _This should be  Edinburgh_

 - https://ep2018.europython.eu/en/registration/volunteers/ has: You should be able to speak some English and perhaps also some **Italian**. _Presumably this is a hangover from Rimini_

**Comment by GadgetSteve** [comment]
https://ep2018.europython.eu/en/contacts/ still gives contact details for Python Italia APS presumably this should be updated to a UK contact.
https://ep2018.europython.eu/en/faq/: Important: Please note that if you are from outside Europe you may need a VISA to enter **Italy** and attend the conference. Please check this before buying your tickets!

**Comment by malemburg** [comment]
Thanks, Steve. I fixed the contacts page and removed Python Italia.

**Comment by matrixise** [comment]
@malemburg I have checked the 4 links, and there is no reference to italy/rimini. Maybe we could close this issue.

**Comment by malemburg** [comment]
On 23.05.2018 14:06, Stéphane Wirtel wrote:
> @malemburg <https://github.com/malemburg> I have checked the 4 links,
> and there is no reference to italy/rimini. Maybe we could close this issue.

Ok.

-- 
Marc-Andre Lemburg
http://www.malemburg.com/
