### ISSUE TITLE
Can't use Google to log into https://ep2018.europython.eu/

### ISSUE THREAD

**Issue by judy2k** [EuroPython/epcon#645]
When I go to the login page, and then click on 'Login with Google' I get a 400 error at the following (slightly modified) URL:

https://accounts.google.com/o/oauth2/auth?scope=openid+email+profile&state=REDACTED&redirect_uri=https://ep2018.europython.eu/complete/google-oauth2/&response_type=code&client_id=REDACTED.apps.googleusercontent.com

**Comment by alexsavio** [comment]
Indeed, I am getting the same.

**Comment by patrick91** [comment]
@malemburg can you update the setting of the Google App?

**Comment by malemburg** [comment]
Fixed in our Google API console.
