### ISSUE TITLE
CSS for highlight is not visible enough.

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#656]
When highlighting something on the website the color of the text changes, but background does not making it really hard to see what's being highlighted. Possible solution: use green for background instead of text color, and make text white).

**Comment by tomviner** [comment]
This is the cause: https://github.com/EuroPython/epcon/blob/55bbdd159f8f2c7b3777599e8cd45658c7cec1b8/p3/static/p6/stylesheets/all.css#L274

Can we go ahead with a PR for that? I'm happy to do it.

Before:
(you have to take my word, that's selected, you can even copy the text, but selecting makes no visual change)
![image](https://user-images.githubusercontent.com/167319/39931542-9d586292-5535-11e8-85b0-673babe67d98.png)

After:
![image](https://user-images.githubusercontent.com/167319/39931614-d64775fc-5535-11e8-8742-6d8987db83eb.png)
