### ISSUE TITLE
Talk voting selection fields are inconsistent

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#668]
All talks default to "not interested". This should probably be "not voted" instead:

![image](https://user-images.githubusercontent.com/6735498/40427448-0be7c13c-5e9e-11e8-836f-9915378bc79b.png)

Additionally, it's not possible to select "not voted" to undo the vote:
![image](https://user-images.githubusercontent.com/6735498/40427430-fed0bbc0-5e9d-11e8-915f-9c8570bf047c.png)

Either "not interested" and "not voted" should be folded into one entry or "not voted" be made a valid option and used as default (having the same vote value as "not interested" I suppose).

**Comment by umgelurgel** [comment]
That's been done for 2019.
