### ISSUE TITLE
Update javascript for cart

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#680]
Two main problems that I found during testing:

* Handling of the Personal/Company dropdown – it basically makes some fields disabled and other enabled – which is correct, but feels weird. Maybe it should hide the unused fields?

* Going over max number of tickets (in this case 6 in a single field,) instead of producing error message it force reloads the page loosing all the information (type of order, coupon codes, amount of tickets) in the process.

**Comment by umgelurgel** [comment]
Closing as the cart implementation has been rewritten.
