### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by barrachri** [EuroPython/epcon#7]
We need to add gunicorn and simplejson.

**Comment by europython-society** [comment]
On 12.02.2015 09:30, Christian Barra wrote:

> We neeed to add gunicorn and simplejson.

simplejson comes with Python 2.7 as "json" module:

https://docs.python.org/2.7/library/json.html

Perhaps it'S better to fix the uses of simplejson to import
json instead ?!

## 

Marc-Andre Lemburg
Director
EuroPython Society
http://www.europython-society.org/

**Comment by d0ugal** [comment]
The simplejson releases are often better as they include more bugfixes and perform better. However, having said that, I'm sure the json module would be good enough for us.

**Comment by barrachri** [comment]
+1 to add simplejson as requirement

**Comment by fpliger** [comment]
for reference: `simplejson` was already added with #8
