### ISSUE TITLE
Unify login for admin and the website

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#732]
Currently login form for admin wants user id (only) and the regular login form on the website wants email (only, won't work with user id).

We should unify that so both work with the email address.

**Comment by umgelurgel** [comment]
Shotgun! :)

**Comment by umgelurgel** [comment]
Submitted a feature request to django-cms to add a feature required for this: https://groups.google.com/forum/#!forum/django-cms-developers. Once it's accepted and I implement the changes, I'll be able to proceed with this ticket.

**Comment by umgelurgel** [comment]
Implemented in https://github.com/EuroPython/epcon/pull/856
