### ISSUE TITLE
Display first names in schedule

### ISSUE THREAD

**Issue by alanderex** [EuroPython/epcon#778]
Please display the full name in the schedule, currently it's abbreviated.
Python conferences are on a first name basis, so we should also show first names.
https://ep2018.europython.eu/p3/schedule/ep2018/
https://ep2018.europython.eu/p3/schedule/ep2018/list/

**Comment by matrixise** [comment]
Fixed here https://github.com/EuroPython/epcon/commit/22f2e67ab4be29d550e1323c2adedf693c5efd08  could you please on https://epstage.europython.eu/p3/schedule/ep2018/ ?

**Comment by artcz** [comment]
This is still valid for a list view -> https://ep2018.europython.eu/p3/schedule/ep2018/list/
