### ISSUE TITLE
Coding header should be utf-8 not UTF-8

### ISSUE THREAD

**Issue by sparkiegeek** [EuroPython/epcon#793]
Many of the coding headers at the top of the modules i.e. [PEP 263](https://www.python.org/dev/peps/pep-0263/) specify `# -*- coding: UTF-8 -*-` which confuses some editors<sup>1</sup>, the canonical spelling is `# -*- coding: utf-8 -*-`

<sup>1</sup> e.g. Emacs https://paste.ubuntu.com/p/yhjNdShvW9/

**Comment by artcz** [comment]
will that also work w/o `-*-`? ie. `# coding: utf-8`

**Comment by sparkiegeek** [comment]
The -*- was adopted in PEP 263 as part of the discussion of the PEP, it matches [Emacs' file variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html).

You can see the change in https://github.com/python/peps/commit/4073747f5d322bceeb2819a730605a8fd19de42f#diff-51522aa3f8caa2f0e158db55d23a83c7

As per the PEP, you can have anything which matches `^[ \t\f]*#.*?coding[:=][ \t]*([-_.a-zA-Z0-9]+)` but as per my religious tendencies, I much prefer the `-*-` approach as it complies with Emacs
