### ISSUE TITLE
Use idempotency key when charging through Stripe to allow safe retries

### ISSUE THREAD

**Issue by sparkiegeek** [EuroPython/epcon#795]
When talking to the Stripe API we should use an `idempotency_key`, as per [Stripe API docs](https://stripe.com/docs/api/python#idempotent_requests) and retry when appropriate to avoid e.g. rate limiting or other transitory errors.

**Comment by umgelurgel** [comment]
Implemented in https://github.com/EuroPython/epcon/commit/6558044d058514592fb0017818a7e0ffdefe58af#diff-dee4dc929f350a50dd539f2373d1d628
