### ISSUE TITLE
Make comments flat again

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#798]
Currently we're using hcomments app (included with epcon src), however we don't really use the hierarchical component, and just use flat comments, which means we could get rid of hcomments w/o any changes to current user experience.

We could also disable public comments, and make comments (on talks – seems like only place where we use it) available only for authenticated users.

Requires adding new tests.

**Comment by umgelurgel** [comment]
We don't seem to use the moderation features (editing/deleting a comment), what about email subscription to comment threads? Asking as that's in `hcomments` and not in `django_comments` - do we want to keep it?

**Comment by artcz** [comment]
I think we don't need it, although email notifiication to the *speaker* that there was a comment about their talk sounds like something to consider in the future.

**Comment by umgelurgel** [comment]
Implemented in https://github.com/EuroPython/epcon/pull/847
