### ISSUE TITLE
Paypal payments don't work

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#80]
Reported on the ML:

Subject: Re: [EuroPython] EuroPython 2015: We've opened the flood gates :-)
Date: Tue, 03 Mar 2015 15:18:55 +0000
From: Roberto Martínez robertomartinezp@gmail.com
To: M.-A. Lemburg mal@europython.eu, EuroPython Mailing List europython@python.org

Hi,

there is a problem with the paypal payment option. Paypal issues this
warning:

"We cannot process this transaction because there is a problem with the
PayPal email address supplied by the seller. Please contact the seller to
resolve the problem. If this payment is for an eBay listing, you can
contact the seller via the "Ask Seller a Question" link on the listing
page. When you have the correct email address, payment can be made at
www.paypal.com."

Best regards,
Roberto

**Comment by aramboi** [comment]
It seems it tries to process the payment on the sandbox/test PayPal subdomain https://www.sandbox.paypal.com/ (look in the address bar)

Might be just a configuration issue.

**Comment by amineck** [comment]
Still doesn't work :(

**Comment by barrachri** [comment]
https://github.com/EuroPython/epcon/pull/92
