### ISSUE TITLE
Remove simplejson and replace with json from stdlib

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#807]
Some places in the code still use external simplejson library. We can remove it and replace with simple 'import json' provided by python's stdlib. This issue is only about that small change.

**Comment by hmajid2301** [comment]
I'll take a look at this one.

**Comment by artcz** [comment]
@hmajid2301 (just a weekly ping to check how is it going. :))

**Comment by hmajid2301** [comment]
Sorry haven't had a chance to take a look yet. Will try to do it in the next week thanks
