### ISSUE TITLE
Update create initial data for dev script with more data.

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#811]
Currently the script creates

* Conference instance
* Basic CMS pages
* Default VAT rate
* Typical fares (based on pre_create_typical_fares_for_conference)

We should expand that with:

* Creating a couple of users (staff, nonstaff) – complete with passwords so we don't have to run createsuperuser as part of provisioning
* Couple of:
  * Orders
  * Tickets
  * Proposals (from CFP)
* Maybe some simple schedule?

Ideas on how to create each of those can be already found in the testsuite.

**Comment by umgelurgel** [comment]
I'll get started on this.

**Comment by artcz** [comment]
Update: we already have some of those in the generator, we still don't create orders, tickets and proposals; we do however create a large set of largely-production-compatible pages in CMS which simplifies many things.

**Comment by umgelurgel** [comment]
Going to close this, it's pretty good as a starting point - new developers can have a reasonable version of the application running locally with the current fixutres.
