### ISSUE TITLE
Review usage of django-tagging and django-taggit

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#860]
related database tables seem to be relatively empty, we're probably not using them at all.

**Comment by artcz** [comment]
Update: we're using taggit with a custom model, there is code that uses tagging library as well, but as mentioned above there's no data.

**Comment by aramboi** [comment]
* `django-tagging` and references to it were removed in PR https://github.com/EuroPython/epcon/pull/1230

* `django-taggit` is used for tags in the talks model - https://github.com/EuroPython/epcon/blob/ep2020/conference/models.py#L691
