### ISSUE TITLE
Fix homepage on mobile

### ISSUE THREAD

**Issue by patrick91** [EuroPython/epcon#869]
From telegram:

![IMAGE 2019-03-15 09:10:37](https://user-images.githubusercontent.com/667029/54420559-33701180-4702-11e9-8c46-3ce8fc16f742.jpg)

> For the mobile portrait perspective, we can use the corresponding vertical logo or just keep the horizontal version as we had last year - probably even better, since you will then be able to see the important dates right on the initial screen.

> Artur, [12 Mar 2019 at 19:22:20]:
> to get this ↑ working on mobile we will need someone to write some additional CSS, because in current template (and it's basically off the shelf bootstrap) what happens with the horizontal logo is that it overflows the screen to the right

> so the logo itself is visible and some of the text, but the rest of it is off the screen.

**Comment by artcz** [comment]
Closing because this is fixed already
