### ISSUE TITLE
CfP updates 2019

### ISSUE THREAD

**Issue by alanderex** [EuroPython/epcon#881]
We will ask for a mobile number for all speakers strictly now. Important updates will be sent to mobile phone - if emails do not work.

- [x] add mobile phone validation to the input field
- [x] reset all phone numbers in the db so we can make sure we do have a recent one

Gender stats, we had to do this manually in the past which is time consuming, please add an text  entry field:
- [x] type your gender

**Comment by artcz** [comment]
Cleared phone numbers today

**Comment by artcz** [comment]
Phone number validation added in be760d02

**Comment by artcz** [comment]
Gender/birthdate fixed in 192e0a1

Copy to be reviewed by @alanderex :)

**Comment by artcz** [comment]
Merged in #880
