### ISSUE TITLE
Configure Stripe for SCA (by September 14)

### ISSUE THREAD

**Issue by umgelurgel** [EuroPython/epcon#895]
> On 14 September 2019, a new European regulatory requirement called  Strong Customer Authentication (SCA) [https://stripe.com/payments/strong-customer-authentication] will introduce two-factor authentication requirements for many online payments in Europe. Payments that aren’t authenticated will be declined by your customers’ banks.

> We’ve released a new payments API and SCA-ready products to help you prepare for this change. To get ready for these new rules and avoid having many European payments declined, you’ll need to make changes to your payment flows and Stripe integration by 14 September 2019. Read our docs to learn more about SCA and the required changes.

> Read the docs [https://stripe.com/docs/strong-customer-authentication]

Looking at the [docs](https://stripe.com/docs/strong-customer-authentication#preparing), as long as we're using the stripe widget, we'll only need to enable the 3D Secure 2 integration in the Stripe dashboard. 

Resources:
 - Flows: https://stripe.com/guides/sca-payment-flows
 - Authentication: https://stripe.com/docs/strong-customer-authentication
 - Webinar: https://stripe.events/sca-webinar

API Changes:
 - Docs: https://stripe.com/docs/payments/payment-intents

Checkout Changes:
 - Docs: https://stripe.com/docs/payments/checkout
 - Flows: https://stripe.com/en-de/guides/sca-payment-flows#e-commerce

Testing tools:
- Testing card numbers triggering SCA auth: https://stripe.com/docs/testing#regulatory-cards

**Comment by artcz** [comment]
Since we're using Charges here https://github.com/EuroPython/epcon/blob/dev/ep2020/conference/payments.py#L22 we probably need to migrate it to payment intents https://stripe.com/docs/payments/payment-intents/migration

**Comment by patrick91** [comment]
Where is charge_for_payment used?

**Comment by artcz** [comment]
@patrick91 https://github.com/EuroPython/epcon/blob/8d0e8d0f50cb326eb2a142c322c58c5f4c7490a4/conference/cart.py#L183
