### ISSUE TITLE
Add another login account doesn't work

### ISSUE THREAD

**Issue by mgedmin** [EuroPython/epcon#90]
1. Log in, go to profile page (https://ep2015.europython.eu/accounts/profile/)
2. Click "Login options"
3. Click "Add another account"

This is what I get:
![screenshot](https://cloud.githubusercontent.com/assets/159967/6479141/e86485a0-c248-11e4-9a95-5f19f49b5706.png)

Chromium also shows a shield icon in the address bar, saying that the website is trying to load unsafe resources (which I guess means JavaScript over HTTP rather than HTTPS), with a "More information" link pointing to https://support.google.com/chrome/answer/1342714

**Comment by aramboi** [comment]
This was removed from the current website. Closing.
