### ISSUE TITLE
Cannot log in with Google

### ISSUE THREAD

**Issue by hugovk** [EuroPython/epcon#906]
# Steps

1. Go to https://ep2019.europython.eu/accounts/signup/?next=

2. Click "Login with Google"

# Expected

Go to Google to authorise/log in.

(Nit: Also button should be "Log in with Google" with a space in "Log in".)

# Actual

> 400. That’s an error.
>
> Error: redirect_uri_mismatch
>
> The redirect URI in the request, https://ep2019.europython.eu/complete/google-oauth2/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/602317069608-2h9hecf8k6le6sp4vtihf7arhsqu3b1a.apps.googleusercontent.com?project=602317069608

![image](https://user-images.githubusercontent.com/1324225/56720137-c8771900-674a-11e9-8210-9557867d0f95.png)

Does the launch domain need adding to the Google console?

**Comment by umgelurgel** [comment]
Thanks for reporting this, @hugovk, and for the detailed description - the login should be fixed now :) If you're still having issues, please reopen.

**Comment by hugovk** [comment]
Almost working!

This time I got to the Google screen, chose which Google account to use, and then got this error:

![image](https://user-images.githubusercontent.com/1324225/56744371-0a22b680-6781-11e9-8ed7-f71a8e62318e.png)

https://ep2019.europython.eu/complete/google-oauth2/?state= `<snip>`

**Comment by hugovk** [comment]
Success! Thank you!
