### ISSUE TITLE
"Report bugs" link somewhere on the website

### ISSUE THREAD

**Issue by mgedmin** [EuroPython/epcon#91]
It'd be nice if people who notice typos or other things like that would know where to report them without having to ask on the mailing list.

A "Report bugs" link in the footer (or perhaps in the Contacts page), pointing to this GitHub repository, would be helpful for that.

**Comment by malemburg** [comment]
We do have this on the contacts page: https://ep2015.europython.eu/en/contacts

**Comment by mgedmin** [comment]
Oops, I failed reading comprehension (after noticing the helpdesk email I jumped to the next headline without reading any of the text).
