### ISSUE TITLE
Invoice changes for EP2019 related the FX rate

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#920]
The accountant mentioned that we have to use the monthly ESTV for converting EUR to CHF on invoices: https://www.estv.admin.ch/estv/de/home/mehrwertsteuer/dienstleistungen/fremdwaehrungskurse/monatsmittelkurse/aktueller-monatsmittelkurs.html

The ECB rate we currently use won't work.

She also mentioned that we don't even have to list the CHF values on the invoice, so I guess easiest would be to remove the CHF values entirely to avoid any confusion when people try to get the VAT back.

**Comment by malemburg** [comment]
The rates are also available XML: http://www.pwebapps.ezv.admin.ch/apps/rates/estv/getavgxml

**Comment by artcz** [comment]
We'll just drop the exchange information from the invoice then and skip the currency handling in epcon.

**Comment by umgelurgel** [comment]
@artcz ok - so I guess this can be resolved as `wontfix`?
