### ISSUE TITLE
Login with Google is broken

### ISSUE THREAD

**Issue by jlaurens** [EuroPython/epcon#928]
05/03/2019
A few days ago, I have successfully logged in with my Google account and submitted a CFP.
Today I can no longer log in with Google. When I click the login with google button, nothing new happens.
I am on OS X 10.13 (french), tested with Safari 12.1, Chrome Version 73.0.3683.103 (Build officiel), Firefox 66.0.3. None works.

**Comment by umgelurgel** [comment]
@jlaurens thanks for reporting it - this should be now fixed, let me know if you continue experiencing issues.

**Comment by jlaurens** [comment]
Google login is available.
Thanks
