### ISSUE TITLE
Request: Edit the name of the speaker while updating the CFP

### ISSUE THREAD

**Issue by jlaurens** [EuroPython/epcon#932]
I have created my account with a google login which have a very special first name and last name : 'Marjôlen Rusée'.
When I submitted the CFP, the speaker name that I provided, 'LAURENS Jérôme' has been somehow modified by adding the first name of the google account name into 'LAURENS Jérôme Rusée', which is not appropriate.
May we have the possibility to edit this name while updating the CFP for example?

**Comment by umgelurgel** [comment]
@jlaurens thanks for reporting this and sorry that your name got mis-adjusted by the system. For now, I can update the name associated with your account manually - to make sure I get the right account, could you send an email to helpdesk at europython.eu with the details of the email of the affected account and the name you'd like to be displayed? I'll take it over from there.

@artcz what do you think about giving users the ability to modify their speaker details, similar to how they can modify their talk proposals during cfp? I could add that and it could be reaused in https://github.com/EuroPython/epcon/pull/925

**Comment by artcz** [comment]
@umgelurgel yes, the data is stored in the AttendeeProfile and should be available for edit at all times, we just need to add a view that renders a correct form.
