### ISSUE TITLE
Blam! A 5xx error occured

### ISSUE THREAD

**Issue by AvdN** [EuroPython/epcon#95]
After paying with stripe (at least I got a nice green background tick for a second or two) I got 
Blam! A 5xx error occured
and no confirmation email whatsoever. Now I am not sure if I paid or not. 
I can retry later today just let me know.

**Comment by barrachri** [comment]
Hi Anthon,
sorry it was my fault :/
Please can you send a ticket to helpdesk@europython.eu ?

Thanks.
