### ISSUE TITLE
Show own talks in talk voting

### ISSUE THREAD

**Issue by The-Compiler** [EuroPython/epcon#958]
From what I've seen in the Europython Telegram group, people are kind of worried when not seeing their own talks on the voting page. The red "Please note that your own submissions are not listed." on the description page probably helps a bit, but it still seems to be confusing.

I think ideally, own talks would be shown, but without the vote buttons.

**Comment by umgelurgel** [comment]
Fixed in https://github.com/EuroPython/epcon/pull/957 (not deployed yet)
