### ISSUE TITLE
Editing some tickets in Django admin gives a 500 error

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#96]
E.g. https://ep2015.europython.eu/admin/conference/ticket/311/

**Comment by oiertwo** [comment]
tickets are related to orders and invoices, you need to delete the order
first, then the ticket. I think the proper order is, invoice (assopy)
->order (assopy) -> ticket (conference).

Try it and tell me if it works.

On 4 March 2015 at 15:47, Marc-Andre Lemburg notifications@github.com
wrote:

> E.g. https://ep2015.europython.eu/admin/conference/ticket/311/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EuroPython/epcon/issues/96.

## 

Oier.

**Comment by malemburg** [comment]
But I don't want to delete a ticket, only check it. Does the 500 error mean that some key relation is broken ?

**Comment by malemburg** [comment]
Just checked: the error also occurs for completed tickets, which most likely have all relations intact.

**Comment by oiertwo** [comment]
Tickets has to be assigned by the user to be available to edit.

**Comment by malemburg** [comment]
Ok, but shouldn't the record still be editable in the Django admin interface ?

The 500 error doesn't look like it's intended behavior ;-)

**Comment by aramboi** [comment]
Doesn't seem to reproduce any more. Assuming it's fixed.
