### ISSUE TITLE
Can't get the reset password email

### ISSUE THREAD

**Issue by ghost** [EuroPython/epcon#980]
Tried multiple times to reset the password due I forgot it, but I never receive an email. Nothing in Spam folder, simply don't receive any message.
I can't login and can't even create a new account.

**Comment by umgelurgel** [comment]
Hey, sorry to hear about the issues you're experiencing - please contact helpdesk at europython.eu, they should be able to help. Going to close this issue for now.

**Comment by ghost** [comment]
Unfortunately I tried the helpdesk first but I've got no answer in 10 days, so I tried this way
