### ISSUE TITLE
Typo "availalbe" in order confirmation email

### ISSUE THREAD

**Issue by bittner** [EuroPython/epcon#982]
The order confirmation email (subject: "EuroPython2019: Order confirmation") sports a typo at the lower half of the email template:

> Your tickets were created and are availalbe on your profile page here:

Should probably read "available" in that sentence.

**Comment by umgelurgel** [comment]
Thanks for catching this, @bittner ! Should be fixed soon :)

**Comment by bittner** [comment]
Thank you for fixing it!
