### ISSUE TITLE
Updating ticket names in the ticket "Configure" screen doesn't work

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#987]
You can edit and save value, but they don't get stored in the ticket record and are gone next time you go to the ticket configuration.

**Comment by malemburg** [comment]
Without this functionality, we don't have any way to put names on tickets for cases where a buyer gets multiple tickets.

**Comment by sm6xmm** [comment]
I'm working on this one, but can't assign myself.

**Comment by umgelurgel** [comment]
Fixed in https://github.com/EuroPython/epcon/pull/998
