### ISSUE TITLE
System needs to properly split first and last name

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#988]
At the moment, the system does not split the first and last name, which will cause issues when sending out attendee emails, creating badges, using tools we have built around the website, etc.

The system does have first_name and last_name in auth_user, but puts the full name into first_name.

I have a script which fixes this again, but the registration logic has to be updated to again ask for first and last name and store this correctly in the user record.

**Comment by umgelurgel** [comment]
Assigning to myself to update the registration form - going to create a separate ticket for cfp.

**Comment by umgelurgel** [comment]
The registration changes have been merged, @malemburg has run the script splitting the names, there's a separate ticket to update the CFP for next year. Going to resolve this.
