### ISSUE TITLE
Normal and social accounts are not merged

### ISSUE THREAD

**Issue by argaen** [EuroPython/epcon#99]
Hi, I had a registered account with my email and a ticket bought. I tried to login with Google and I can't login anymore with username/password. Also, the ticket is gone from my profile. I still have an old session with the ticket in my profile though.

Am I the only one? =)

**Comment by abrahammartin** [comment]
Happened to me too, but in my case I didn't have an old session opened. Lost the ticket, emailed helpdesk.

**Comment by argaen** [comment]
Did they fix it?

**Comment by malemburg** [comment]
Please email the helpdesk to try to get this resolved. Thanks.

**Comment by abrahammartin** [comment]
No, it is not fixed yet. And helpdesk is not answering emails, I opened a helpdesk ticket 8 days ago, no answer yet...

**Comment by barrachri** [comment]
Hi Abraham !
sorry but we are in the middle of milions things and we are less than 10 people that are doing all is needed for the conference !
Please be patience.

**Comment by shimizukawa** [comment]
I've faced the same issue.
My account is already recovered by helpdesk staff after I sent a email to report it.

It would be better if account overloading is just avoided.

**Comment by barrachri** [comment]
Hi all,
the issue is simple, if you have an email+password user and then use "login with gmail" you'll get a new user with the same email and the weird result that you can't login with your email+password user.

So if you have this problem the best we can do for now it's to delete one user (==> helpdesk).

**Comment by argaen** [comment]
Yeah but the problem is that I have the ticket I bought in the account with username+password. Can you move it to the social account so you can delete the user safely?
